/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by happy-dom-codegen from Chromium's css_properties.json5.
 * Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5
 */
/**
 * Parses a CSS text string (e.g. from an element's style attribute)
 * into individual property declarations.
 */
export default class CSSStyleDeclarationCSSParser {
	/**
	 * Parse a CSS text string into rules.
	 *
	 * @param cssText CSS text to parse.
	 * @returns Parsed result with rules and custom properties.
	 */
	static parse(cssText) {
		const rules = [];
		const properties = {};
		if (!cssText || typeof cssText !== 'string') {
			return { rules, properties };
		}
		// Simple state-machine parser for better handling of edge cases
		let i = 0;
		const len = cssText.length;
		while (i < len) {
			// Skip whitespace
			while (i < len && /\s/.test(cssText[i])) {
				i++;
			}
			if (i >= len) {
				break;
			}
			// Find the colon separating name from value
			const colonIndex = cssText.indexOf(':', i);
			if (colonIndex === -1) {
				break;
			}
			const name = cssText.slice(i, colonIndex).trim();
			if (!name) {
				i = colonIndex + 1;
				continue;
			}
			// Parse the value — must handle parens, quotes, and semicolons
			const valueStart = colonIndex + 1;
			let j = valueStart;
			let parenDepth = 0;
			let inSingleQuote = false;
			let inDoubleQuote = false;
			while (j < len) {
				const ch = cssText[j];
				if (inSingleQuote) {
					if (ch === "'" && cssText[j - 1] !== '\\') {
						inSingleQuote = false;
					}
				} else if (inDoubleQuote) {
					if (ch === '"' && cssText[j - 1] !== '\\') {
						inDoubleQuote = false;
					}
				} else if (ch === "'") {
					inSingleQuote = true;
				} else if (ch === '"') {
					inDoubleQuote = true;
				} else if (ch === '(') {
					parenDepth++;
				} else if (ch === ')') {
					parenDepth--;
				} else if (ch === ';' && parenDepth === 0) {
					break;
				}
				j++;
			}
			let rawValue = cssText.slice(valueStart, j).trim();
			let important = false;
			// Check for !important
			if (rawValue.endsWith('!important')) {
				rawValue = rawValue.slice(0, -'!important'.length).trim();
				important = true;
			} else {
				const impMatch = rawValue.match(/\s*!\s*important\s*$/i);
				if (impMatch) {
					rawValue = rawValue.slice(0, -impMatch[0].length).trim();
					important = true;
				}
			}
			if (rawValue) {
				const lowerName = name.toLowerCase();
				rules.push({ name: lowerName, value: rawValue, important });
				if (lowerName.startsWith('--')) {
					properties[lowerName] = rawValue;
				}
			}
			i = j + 1; // skip semicolon
		}
		return { rules, properties };
	}
}
