/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by happy-dom-codegen from Chromium's css_properties.json5.
 * Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5
 */
/**
 * Shorthand → ordered longhand property names.
 * Used by PropertyManager for expansion (B1) and recomposition (B2).
 */
export const CSS_SHORTHAND_TO_LONGHANDS = {
	'interest-delay': ['interest-delay-start', 'interest-delay-end'],
	'text-box': ['text-box-trim', 'text-box-edge'],
	'text-spacing': ['text-autospace', 'text-spacing-trim'],
	'line-clamp': ['max-lines', 'block-ellipsis', 'continue'],
	'-alternative-webkit-line-clamp': ['max-lines', 'block-ellipsis', 'continue'],
	'white-space': ['white-space-collapse', 'text-wrap-mode'],
	'text-wrap': ['text-wrap-mode', 'text-wrap-style'],
	animation: [
		'animation-duration',
		'animation-timing-function',
		'animation-delay',
		'animation-iteration-count',
		'animation-direction',
		'animation-fill-mode',
		'animation-play-state',
		'animation-name',
		'animation-timeline',
		'animation-range-start',
		'animation-range-end'
	],
	'animation-range': ['animation-range-start', 'animation-range-end'],
	background: [
		'background-image',
		'background-position-x',
		'background-position-y',
		'background-size',
		'background-repeat',
		'background-attachment',
		'background-origin',
		'background-clip',
		'background-color'
	],
	'background-position': ['background-position-x', 'background-position-y'],
	border: [
		'border-top-color',
		'border-top-style',
		'border-top-width',
		'border-right-color',
		'border-right-style',
		'border-right-width',
		'border-bottom-color',
		'border-bottom-style',
		'border-bottom-width',
		'border-left-color',
		'border-left-style',
		'border-left-width',
		'border-image-source',
		'border-image-slice',
		'border-image-width',
		'border-image-outset',
		'border-image-repeat'
	],
	'border-block': [
		'border-block-start-color',
		'border-block-start-style',
		'border-block-start-width',
		'border-block-end-color',
		'border-block-end-style',
		'border-block-end-width'
	],
	'border-block-color': ['border-block-start-color', 'border-block-end-color'],
	'border-block-end': [
		'border-block-end-width',
		'border-block-end-style',
		'border-block-end-color'
	],
	'border-block-start': [
		'border-block-start-width',
		'border-block-start-style',
		'border-block-start-color'
	],
	'border-block-style': ['border-block-start-style', 'border-block-end-style'],
	'border-block-width': ['border-block-start-width', 'border-block-end-width'],
	'border-bottom': ['border-bottom-width', 'border-bottom-style', 'border-bottom-color'],
	'border-color': [
		'border-top-color',
		'border-right-color',
		'border-bottom-color',
		'border-left-color'
	],
	'border-image': [
		'border-image-source',
		'border-image-slice',
		'border-image-width',
		'border-image-outset',
		'border-image-repeat'
	],
	'border-inline': [
		'border-inline-start-color',
		'border-inline-start-style',
		'border-inline-start-width',
		'border-inline-end-color',
		'border-inline-end-style',
		'border-inline-end-width'
	],
	'border-inline-color': ['border-inline-start-color', 'border-inline-end-color'],
	'border-inline-end': [
		'border-inline-end-width',
		'border-inline-end-style',
		'border-inline-end-color'
	],
	'border-inline-start': [
		'border-inline-start-width',
		'border-inline-start-style',
		'border-inline-start-color'
	],
	'border-inline-style': ['border-inline-start-style', 'border-inline-end-style'],
	'border-inline-width': ['border-inline-start-width', 'border-inline-end-width'],
	'border-left': ['border-left-width', 'border-left-style', 'border-left-color'],
	'border-radius': [
		'border-top-left-radius',
		'border-top-right-radius',
		'border-bottom-right-radius',
		'border-bottom-left-radius'
	],
	'border-right': ['border-right-width', 'border-right-style', 'border-right-color'],
	'border-spacing': ['-webkit-border-horizontal-spacing', '-webkit-border-vertical-spacing'],
	'border-style': [
		'border-top-style',
		'border-right-style',
		'border-bottom-style',
		'border-left-style'
	],
	'border-top': ['border-top-width', 'border-top-style', 'border-top-color'],
	'border-width': [
		'border-top-width',
		'border-right-width',
		'border-bottom-width',
		'border-left-width'
	],
	'column-rule-edge-inset': ['column-rule-edge-inset-start', 'column-rule-edge-inset-end'],
	'column-rule-inset-end': ['column-rule-edge-inset-end', 'column-rule-interior-inset-end'],
	'column-rule-inset-start': ['column-rule-edge-inset-start', 'column-rule-interior-inset-start'],
	'column-rule-interior-inset': [
		'column-rule-interior-inset-start',
		'column-rule-interior-inset-end'
	],
	'contain-intrinsic-size': ['contain-intrinsic-width', 'contain-intrinsic-height'],
	container: ['container-name', 'container-type'],
	'corner-top-shape': ['corner-top-left-shape', 'corner-top-right-shape'],
	'corner-right-shape': ['corner-top-right-shape', 'corner-bottom-right-shape'],
	'corner-bottom-shape': ['corner-bottom-left-shape', 'corner-bottom-right-shape'],
	'corner-left-shape': ['corner-top-left-shape', 'corner-bottom-left-shape'],
	'corner-block-start-shape': ['corner-start-start-shape', 'corner-start-end-shape'],
	'corner-block-end-shape': ['corner-end-start-shape', 'corner-end-end-shape'],
	'corner-inline-start-shape': ['corner-start-start-shape', 'corner-end-start-shape'],
	'corner-inline-end-shape': ['corner-start-end-shape', 'corner-end-end-shape'],
	'corner-shape': [
		'corner-top-left-shape',
		'corner-top-right-shape',
		'corner-bottom-right-shape',
		'corner-bottom-left-shape'
	],
	corners: [
		'border-top-left-radius',
		'corner-top-left-shape',
		'border-top-right-radius',
		'corner-top-right-shape',
		'border-bottom-right-radius',
		'corner-bottom-right-shape',
		'border-bottom-left-radius',
		'corner-bottom-left-shape'
	],
	flex: ['flex-grow', 'flex-shrink', 'flex-basis'],
	'flex-flow': ['flex-direction', 'flex-wrap'],
	font: [
		'font-style',
		'font-variant-ligatures',
		'font-variant-caps',
		'font-variant-numeric',
		'font-variant-east-asian',
		'font-variant-alternates',
		'font-variant-position',
		'font-variant-emoji',
		'font-weight',
		'font-stretch',
		'font-size',
		'line-height',
		'font-family',
		'font-optical-sizing',
		'font-size-adjust',
		'font-kerning',
		'font-feature-settings',
		'font-variation-settings',
		'font-language-override'
	],
	'font-variant': [
		'font-variant-ligatures',
		'font-variant-caps',
		'font-variant-alternates',
		'font-variant-numeric',
		'font-variant-east-asian',
		'font-variant-position',
		'font-variant-emoji'
	],
	'font-synthesis': ['font-synthesis-weight', 'font-synthesis-style', 'font-synthesis-small-caps'],
	grid: [
		'grid-template-rows',
		'grid-template-columns',
		'grid-template-areas',
		'grid-auto-flow',
		'grid-auto-rows',
		'grid-auto-columns'
	],
	'place-content': ['align-content', 'justify-content'],
	'place-items': ['align-items', 'justify-items'],
	'place-self': ['align-self', 'justify-self'],
	gap: ['row-gap', 'column-gap'],
	'grid-area': ['grid-row-start', 'grid-column-start', 'grid-row-end', 'grid-column-end'],
	'grid-column': ['grid-column-start', 'grid-column-end'],
	'grid-lanes': [
		'grid-template-areas',
		'grid-template-columns',
		'grid-template-rows',
		'grid-lanes-direction'
	],
	'grid-row': ['grid-row-start', 'grid-row-end'],
	'grid-template': ['grid-template-rows', 'grid-template-columns', 'grid-template-areas'],
	inset: ['top', 'right', 'bottom', 'left'],
	'inset-block': ['inset-block-start', 'inset-block-end'],
	'inset-inline': ['inset-inline-start', 'inset-inline-end'],
	'list-style': ['list-style-position', 'list-style-image', 'list-style-type'],
	margin: ['margin-top', 'margin-right', 'margin-bottom', 'margin-left'],
	'margin-block': ['margin-block-start', 'margin-block-end'],
	'margin-inline': ['margin-inline-start', 'margin-inline-end'],
	marker: ['marker-start', 'marker-mid', 'marker-end'],
	offset: ['offset-position', 'offset-path', 'offset-distance', 'offset-rotate', 'offset-anchor'],
	outline: ['outline-color', 'outline-style', 'outline-width'],
	overflow: ['overflow-x', 'overflow-y'],
	'overscroll-behavior': ['overscroll-behavior-x', 'overscroll-behavior-y'],
	padding: ['padding-top', 'padding-right', 'padding-bottom', 'padding-left'],
	'padding-block': ['padding-block-start', 'padding-block-end'],
	'padding-inline': ['padding-inline-start', 'padding-inline-end'],
	'page-break-after': ['break-after'],
	'page-break-before': ['break-before'],
	'page-break-inside': ['break-inside'],
	'position-try': ['position-try-order', 'position-try-fallbacks'],
	'row-rule-edge-inset': ['row-rule-edge-inset-start', 'row-rule-edge-inset-end'],
	'row-rule-inset-end': ['row-rule-edge-inset-end', 'row-rule-interior-inset-end'],
	'row-rule-inset-start': ['row-rule-edge-inset-start', 'row-rule-interior-inset-start'],
	'row-rule-interior-inset': ['row-rule-interior-inset-start', 'row-rule-interior-inset-end'],
	rule: [
		'column-rule-width',
		'column-rule-style',
		'column-rule-color',
		'row-rule-width',
		'row-rule-style',
		'row-rule-color'
	],
	'rule-break': ['row-rule-break', 'column-rule-break'],
	'rule-color': ['column-rule-color', 'row-rule-color'],
	'rule-edge-inset': [
		'row-rule-edge-inset-start',
		'row-rule-edge-inset-end',
		'column-rule-edge-inset-start',
		'column-rule-edge-inset-end'
	],
	'rule-interior-inset': [
		'row-rule-interior-inset-start',
		'row-rule-interior-inset-end',
		'column-rule-interior-inset-start',
		'column-rule-interior-inset-end'
	],
	'rule-inset-end': [
		'column-rule-edge-inset-end',
		'column-rule-interior-inset-end',
		'row-rule-edge-inset-end',
		'row-rule-interior-inset-end'
	],
	'rule-inset-start': [
		'column-rule-edge-inset-start',
		'column-rule-interior-inset-start',
		'row-rule-edge-inset-start',
		'row-rule-interior-inset-start'
	],
	'column-rule-inset': [
		'column-rule-edge-inset-start',
		'column-rule-edge-inset-end',
		'column-rule-interior-inset-start',
		'column-rule-interior-inset-end'
	],
	'row-rule-inset': [
		'row-rule-edge-inset-start',
		'row-rule-edge-inset-end',
		'row-rule-interior-inset-start',
		'row-rule-interior-inset-end'
	],
	'rule-inset': [
		'row-rule-edge-inset-start',
		'row-rule-edge-inset-end',
		'row-rule-interior-inset-start',
		'row-rule-interior-inset-end',
		'column-rule-edge-inset-start',
		'column-rule-edge-inset-end',
		'column-rule-interior-inset-start',
		'column-rule-interior-inset-end'
	],
	'rule-width': ['column-rule-width', 'row-rule-width'],
	'rule-style': ['column-rule-style', 'row-rule-style'],
	'rule-visibility-items': ['column-rule-visibility-items', 'row-rule-visibility-items'],
	'scroll-margin': [
		'scroll-margin-top',
		'scroll-margin-right',
		'scroll-margin-bottom',
		'scroll-margin-left'
	],
	'scroll-margin-block': ['scroll-margin-block-start', 'scroll-margin-block-end'],
	'scroll-margin-inline': ['scroll-margin-inline-start', 'scroll-margin-inline-end'],
	'scroll-padding': [
		'scroll-padding-top',
		'scroll-padding-right',
		'scroll-padding-bottom',
		'scroll-padding-left'
	],
	'scroll-padding-block': ['scroll-padding-block-start', 'scroll-padding-block-end'],
	'scroll-padding-inline': ['scroll-padding-inline-start', 'scroll-padding-inline-end'],
	'scroll-timeline': ['scroll-timeline-name', 'scroll-timeline-axis'],
	'text-decoration': [
		'text-decoration-line',
		'text-decoration-thickness',
		'text-decoration-style',
		'text-decoration-color'
	],
	transition: [
		'transition-property',
		'transition-duration',
		'transition-timing-function',
		'transition-delay',
		'transition-behavior'
	],
	'view-timeline': ['view-timeline-name', 'view-timeline-axis', 'view-timeline-inset'],
	'-webkit-column-break-after': ['break-after'],
	'-webkit-column-break-before': ['break-before'],
	'-webkit-column-break-inside': ['break-inside'],
	'column-rule': ['column-rule-width', 'column-rule-style', 'column-rule-color'],
	'row-rule': ['row-rule-width', 'row-rule-style', 'row-rule-color'],
	columns: ['column-width', 'column-count', 'column-height', 'column-wrap'],
	mask: [
		'mask-image',
		'-webkit-mask-position-x',
		'-webkit-mask-position-y',
		'mask-size',
		'mask-repeat',
		'mask-origin',
		'mask-clip',
		'mask-composite',
		'mask-mode'
	],
	'-webkit-mask-box-image': [
		'-webkit-mask-box-image-source',
		'-webkit-mask-box-image-slice',
		'-webkit-mask-box-image-width',
		'-webkit-mask-box-image-outset',
		'-webkit-mask-box-image-repeat'
	],
	'mask-position': ['-webkit-mask-position-x', '-webkit-mask-position-y'],
	'text-emphasis': ['text-emphasis-style', 'text-emphasis-color'],
	'timeline-trigger': [
		'timeline-trigger-name',
		'timeline-trigger-source',
		'timeline-trigger-activation-range-start',
		'timeline-trigger-activation-range-end',
		'timeline-trigger-active-range-start',
		'timeline-trigger-active-range-end'
	],
	'timeline-trigger-activation-range': [
		'timeline-trigger-activation-range-start',
		'timeline-trigger-activation-range-end'
	],
	'timeline-trigger-active-range': [
		'timeline-trigger-active-range-start',
		'timeline-trigger-active-range-end'
	],
	'-webkit-text-stroke': ['-webkit-text-stroke-width', '-webkit-text-stroke-color']
};
/**
 * Longhand → shorthands that contain it.
 */
export const CSS_LONGHAND_TO_SHORTHANDS = {};
for (const [shorthand, longhands] of Object.entries(CSS_SHORTHAND_TO_LONGHANDS)) {
	for (const lh of longhands) {
		if (!CSS_LONGHAND_TO_SHORTHANDS[lh]) {
			CSS_LONGHAND_TO_SHORTHANDS[lh] = [];
		}
		CSS_LONGHAND_TO_SHORTHANDS[lh].push(shorthand);
	}
}
