/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by happy-dom-codegen from Chromium's css_properties.json5.
 * Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5
 */
/**
 * All non-internal CSS longhand properties.
 */
export const CSS_LONGHAND_PROPERTIES = {
	'animation-composition': {
		name: 'animation-composition',
		camelCase: 'animationComposition',
		inherited: false,
		keywords: ['replace', 'add', 'accumulate'],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-delay': {
		name: 'animation-delay',
		camelCase: 'animationDelay',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-direction': {
		name: 'animation-direction',
		camelCase: 'animationDirection',
		inherited: false,
		keywords: ['normal', 'reverse', 'alternate', 'alternate-reverse'],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'animation-duration': {
		name: 'animation-duration',
		camelCase: 'animationDuration',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-fill-mode': {
		name: 'animation-fill-mode',
		camelCase: 'animationFillMode',
		inherited: false,
		keywords: ['none', 'forwards', 'backwards', 'both'],
		initialValue: 'none',
		acceptsNegative: false
	},
	'animation-iteration-count': {
		name: 'animation-iteration-count',
		camelCase: 'animationIterationCount',
		inherited: false,
		keywords: ['infinite'],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-name': {
		name: 'animation-name',
		camelCase: 'animationName',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-play-state': {
		name: 'animation-play-state',
		camelCase: 'animationPlayState',
		inherited: false,
		keywords: ['running', 'paused'],
		initialValue: 'running',
		acceptsNegative: false
	},
	'animation-range-start': {
		name: 'animation-range-start',
		camelCase: 'animationRangeStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-range-end': {
		name: 'animation-range-end',
		camelCase: 'animationRangeEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-timeline': {
		name: 'animation-timeline',
		camelCase: 'animationTimeline',
		inherited: false,
		keywords: ['none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-timing-function': {
		name: 'animation-timing-function',
		camelCase: 'animationTimingFunction',
		inherited: false,
		keywords: [
			'linear',
			'ease',
			'ease-in',
			'ease-out',
			'ease-in-out',
			'jump-both',
			'jump-end',
			'jump-none',
			'jump-start',
			'step-start',
			'step-end'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'animation-trigger': {
		name: 'animation-trigger',
		camelCase: 'animationTrigger',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-trigger-name': {
		name: 'timeline-trigger-name',
		camelCase: 'timelineTriggerName',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-trigger-activation-range-start': {
		name: 'timeline-trigger-activation-range-start',
		camelCase: 'timelineTriggerActivationRangeStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-trigger-activation-range-end': {
		name: 'timeline-trigger-activation-range-end',
		camelCase: 'timelineTriggerActivationRangeEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-trigger-active-range-start': {
		name: 'timeline-trigger-active-range-start',
		camelCase: 'timelineTriggerActiveRangeStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-trigger-active-range-end': {
		name: 'timeline-trigger-active-range-end',
		camelCase: 'timelineTriggerActiveRangeEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-trigger-source': {
		name: 'timeline-trigger-source',
		camelCase: 'timelineTriggerSource',
		inherited: false,
		keywords: ['none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'transition-delay': {
		name: 'transition-delay',
		camelCase: 'transitionDelay',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'transition-duration': {
		name: 'transition-duration',
		camelCase: 'transitionDuration',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'transition-property': {
		name: 'transition-property',
		camelCase: 'transitionProperty',
		inherited: false,
		keywords: ['none'],
		initialValue: 'all',
		acceptsNegative: false
	},
	'transition-behavior': {
		name: 'transition-behavior',
		camelCase: 'transitionBehavior',
		inherited: false,
		keywords: ['normal', 'allow-discrete'],
		initialValue: '',
		acceptsNegative: false
	},
	'transition-timing-function': {
		name: 'transition-timing-function',
		camelCase: 'transitionTimingFunction',
		inherited: false,
		keywords: [
			'linear',
			'ease',
			'ease-in',
			'ease-out',
			'ease-in-out',
			'jump-both',
			'jump-end',
			'jump-none',
			'jump-start',
			'step-start',
			'step-end'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'trigger-scope': {
		name: 'trigger-scope',
		camelCase: 'triggerScope',
		inherited: false,
		keywords: ['none', 'all'],
		initialValue: '',
		acceptsNegative: false
	},
	color: {
		name: 'color',
		camelCase: 'color',
		inherited: true,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	direction: {
		name: 'direction',
		camelCase: 'direction',
		inherited: true,
		keywords: ['ltr', 'rtl'],
		initialValue: 'ltr',
		acceptsNegative: false
	},
	'font-family': {
		name: 'font-family',
		camelCase: 'fontFamily',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'font-kerning': {
		name: 'font-kerning',
		camelCase: 'fontKerning',
		inherited: true,
		keywords: ['auto', 'normal', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-optical-sizing': {
		name: 'font-optical-sizing',
		camelCase: 'fontOpticalSizing',
		inherited: true,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-palette': {
		name: 'font-palette',
		camelCase: 'fontPalette',
		inherited: true,
		keywords: ['normal', 'light', 'dark'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-size': {
		name: 'font-size',
		camelCase: 'fontSize',
		inherited: true,
		keywords: [
			'xx-small',
			'x-small',
			'small',
			'medium',
			'large',
			'x-large',
			'xx-large',
			'xxx-large',
			'larger',
			'smaller',
			'-webkit-xxx-large'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'font-size-adjust': {
		name: 'font-size-adjust',
		camelCase: 'fontSizeAdjust',
		inherited: true,
		keywords: ['none', 'ex-height', 'cap-height', 'ch-width', 'ic-width', 'ic-height', 'from-font'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-stretch': {
		name: 'font-stretch',
		camelCase: 'fontStretch',
		inherited: true,
		keywords: [
			'normal',
			'ultra-condensed',
			'extra-condensed',
			'condensed',
			'semi-condensed',
			'semi-expanded',
			'expanded',
			'extra-expanded',
			'ultra-expanded'
		],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'font-style': {
		name: 'font-style',
		camelCase: 'fontStyle',
		inherited: true,
		keywords: ['normal', 'italic', 'oblique'],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'font-variant-ligatures': {
		name: 'font-variant-ligatures',
		camelCase: 'fontVariantLigatures',
		inherited: true,
		keywords: [
			'normal',
			'none',
			'common-ligatures',
			'no-common-ligatures',
			'discretionary-ligatures',
			'no-discretionary-ligatures',
			'historical-ligatures',
			'no-historical-ligatures',
			'contextual',
			'no-contextual'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'font-variant-caps': {
		name: 'font-variant-caps',
		camelCase: 'fontVariantCaps',
		inherited: true,
		keywords: [
			'normal',
			'small-caps',
			'all-small-caps',
			'petite-caps',
			'all-petite-caps',
			'unicase',
			'titling-caps'
		],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'font-variant-east-asian': {
		name: 'font-variant-east-asian',
		camelCase: 'fontVariantEastAsian',
		inherited: true,
		keywords: [
			'normal',
			'jis78',
			'jis83',
			'jis90',
			'jis04',
			'simplified',
			'traditional',
			'full-width',
			'proportional-width',
			'ruby'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'font-variant-numeric': {
		name: 'font-variant-numeric',
		camelCase: 'fontVariantNumeric',
		inherited: true,
		keywords: [
			'normal',
			'lining-nums',
			'oldstyle-nums',
			'proportional-nums',
			'tabular-nums',
			'diagonal-fractions',
			'stacked-fractions',
			'ordinal',
			'slashed-zero'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'font-variant-alternates': {
		name: 'font-variant-alternates',
		camelCase: 'fontVariantAlternates',
		inherited: true,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-weight': {
		name: 'font-weight',
		camelCase: 'fontWeight',
		inherited: true,
		keywords: ['normal', 'bold', 'bolder', 'lighter'],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'font-synthesis-weight': {
		name: 'font-synthesis-weight',
		camelCase: 'fontSynthesisWeight',
		inherited: true,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-synthesis-style': {
		name: 'font-synthesis-style',
		camelCase: 'fontSynthesisStyle',
		inherited: true,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-synthesis-small-caps': {
		name: 'font-synthesis-small-caps',
		camelCase: 'fontSynthesisSmallCaps',
		inherited: true,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-feature-settings': {
		name: 'font-feature-settings',
		camelCase: 'fontFeatureSettings',
		inherited: true,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-variation-settings': {
		name: 'font-variation-settings',
		camelCase: 'fontVariationSettings',
		inherited: true,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-language-override': {
		name: 'font-language-override',
		camelCase: 'fontLanguageOverride',
		inherited: true,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-variant-emoji': {
		name: 'font-variant-emoji',
		camelCase: 'fontVariantEmoji',
		inherited: true,
		keywords: ['normal', 'text', 'emoji', 'unicode'],
		initialValue: '',
		acceptsNegative: false
	},
	'font-variant-position': {
		name: 'font-variant-position',
		camelCase: 'fontVariantPosition',
		inherited: true,
		keywords: ['normal', 'sub', 'super'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-font-smoothing': {
		name: '-webkit-font-smoothing',
		camelCase: 'webkitFontSmoothing',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'forced-color-adjust': {
		name: 'forced-color-adjust',
		camelCase: 'forcedColorAdjust',
		inherited: true,
		keywords: ['auto', 'none', 'preserve-parent-color'],
		initialValue: '',
		acceptsNegative: false
	},
	'field-sizing': {
		name: 'field-sizing',
		camelCase: 'fieldSizing',
		inherited: false,
		keywords: ['fixed', 'content'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-locale': {
		name: '-webkit-locale',
		camelCase: 'webkitLocale',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'math-depth': {
		name: 'math-depth',
		camelCase: 'mathDepth',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'text-orientation': {
		name: 'text-orientation',
		camelCase: 'textOrientation',
		inherited: true,
		keywords: ['sideways', 'mixed', 'upright'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-orientation': {
		name: '-webkit-text-orientation',
		camelCase: 'webkitTextOrientation',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'writing-mode': {
		name: 'writing-mode',
		camelCase: 'writingMode',
		inherited: true,
		keywords: ['horizontal-tb', 'vertical-rl', 'vertical-lr', 'sideways-rl', 'sideways-lr'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-writing-mode': {
		name: '-webkit-writing-mode',
		camelCase: 'webkitWritingMode',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'text-rendering': {
		name: 'text-rendering',
		camelCase: 'textRendering',
		inherited: true,
		keywords: ['auto', 'optimizespeed', 'optimizelegibility', 'geometricprecision'],
		initialValue: '',
		acceptsNegative: false
	},
	zoom: {
		name: 'zoom',
		camelCase: 'zoom',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'accent-color': {
		name: 'accent-color',
		camelCase: 'accentColor',
		inherited: true,
		keywords: ['auto', 'currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'align-content': {
		name: 'align-content',
		camelCase: 'alignContent',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'align-items': {
		name: 'align-items',
		camelCase: 'alignItems',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'alignment-baseline': {
		name: 'alignment-baseline',
		camelCase: 'alignmentBaseline',
		inherited: false,
		keywords: [
			'auto',
			'baseline',
			'alphabetic',
			'ideographic',
			'middle',
			'central',
			'mathematical',
			'before-edge',
			'text-before-edge',
			'after-edge',
			'text-after-edge',
			'hanging'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'align-self': {
		name: 'align-self',
		camelCase: 'alignSelf',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'anchor-name': {
		name: 'anchor-name',
		camelCase: 'anchorName',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'anchor-scope': {
		name: 'anchor-scope',
		camelCase: 'anchorScope',
		inherited: false,
		keywords: ['none', 'all'],
		initialValue: '',
		acceptsNegative: false
	},
	'aspect-ratio': {
		name: 'aspect-ratio',
		camelCase: 'aspectRatio',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'backdrop-filter': {
		name: 'backdrop-filter',
		camelCase: 'backdropFilter',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'backface-visibility': {
		name: 'backface-visibility',
		camelCase: 'backfaceVisibility',
		inherited: false,
		keywords: ['visible', 'hidden'],
		initialValue: 'visible',
		acceptsNegative: false
	},
	'background-attachment': {
		name: 'background-attachment',
		camelCase: 'backgroundAttachment',
		inherited: false,
		keywords: ['scroll', 'fixed', 'local'],
		initialValue: '',
		acceptsNegative: false
	},
	'background-blend-mode': {
		name: 'background-blend-mode',
		camelCase: 'backgroundBlendMode',
		inherited: false,
		keywords: [
			'normal',
			'multiply',
			'screen',
			'overlay',
			'darken',
			'lighten',
			'color-dodge',
			'color-burn',
			'hard-light',
			'soft-light',
			'difference',
			'exclusion',
			'hue',
			'saturation',
			'color',
			'luminosity'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'background-clip': {
		name: 'background-clip',
		camelCase: 'backgroundClip',
		inherited: false,
		keywords: ['border-box', 'padding-box', 'content-box', 'text', 'border-area'],
		initialValue: '',
		acceptsNegative: false
	},
	'background-color': {
		name: 'background-color',
		camelCase: 'backgroundColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'background-image': {
		name: 'background-image',
		camelCase: 'backgroundImage',
		inherited: false,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'background-origin': {
		name: 'background-origin',
		camelCase: 'backgroundOrigin',
		inherited: false,
		keywords: ['border-box', 'padding-box', 'content-box'],
		initialValue: '',
		acceptsNegative: false
	},
	'background-position-x': {
		name: 'background-position-x',
		camelCase: 'backgroundPositionX',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'background-position-y': {
		name: 'background-position-y',
		camelCase: 'backgroundPositionY',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'background-repeat': {
		name: 'background-repeat',
		camelCase: 'backgroundRepeat',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'background-size': {
		name: 'background-size',
		camelCase: 'backgroundSize',
		inherited: false,
		keywords: ['auto', 'cover', 'contain'],
		initialValue: '',
		acceptsNegative: false
	},
	'baseline-shift': {
		name: 'baseline-shift',
		camelCase: 'baselineShift',
		inherited: false,
		keywords: ['baseline', 'sub', 'super'],
		initialValue: '',
		acceptsNegative: false
	},
	'baseline-source': {
		name: 'baseline-source',
		camelCase: 'baselineSource',
		inherited: false,
		keywords: ['auto', 'first', 'last'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-bottom-color': {
		name: 'border-bottom-color',
		camelCase: 'borderBottomColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-bottom-left-radius': {
		name: 'border-bottom-left-radius',
		camelCase: 'borderBottomLeftRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-bottom-right-radius': {
		name: 'border-bottom-right-radius',
		camelCase: 'borderBottomRightRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-bottom-style': {
		name: 'border-bottom-style',
		camelCase: 'borderBottomStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'border-bottom-width': {
		name: 'border-bottom-width',
		camelCase: 'borderBottomWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '0px',
		acceptsNegative: false
	},
	'border-collapse': {
		name: 'border-collapse',
		camelCase: 'borderCollapse',
		inherited: true,
		keywords: ['separate', 'collapse'],
		initialValue: 'separate',
		acceptsNegative: false
	},
	'border-image-outset': {
		name: 'border-image-outset',
		camelCase: 'borderImageOutset',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-image-repeat': {
		name: 'border-image-repeat',
		camelCase: 'borderImageRepeat',
		inherited: false,
		keywords: ['stretch', 'repeat', 'round', 'space'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-image-slice': {
		name: 'border-image-slice',
		camelCase: 'borderImageSlice',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-image-source': {
		name: 'border-image-source',
		camelCase: 'borderImageSource',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-image-width': {
		name: 'border-image-width',
		camelCase: 'borderImageWidth',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-left-color': {
		name: 'border-left-color',
		camelCase: 'borderLeftColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-left-style': {
		name: 'border-left-style',
		camelCase: 'borderLeftStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'border-left-width': {
		name: 'border-left-width',
		camelCase: 'borderLeftWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '0px',
		acceptsNegative: false
	},
	'border-right-color': {
		name: 'border-right-color',
		camelCase: 'borderRightColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-right-style': {
		name: 'border-right-style',
		camelCase: 'borderRightStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'border-right-width': {
		name: 'border-right-width',
		camelCase: 'borderRightWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '0px',
		acceptsNegative: false
	},
	'border-top-color': {
		name: 'border-top-color',
		camelCase: 'borderTopColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'border-top-left-radius': {
		name: 'border-top-left-radius',
		camelCase: 'borderTopLeftRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-top-right-radius': {
		name: 'border-top-right-radius',
		camelCase: 'borderTopRightRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-top-style': {
		name: 'border-top-style',
		camelCase: 'borderTopStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'border-top-width': {
		name: 'border-top-width',
		camelCase: 'borderTopWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '0px',
		acceptsNegative: false
	},
	'border-shape': {
		name: 'border-shape',
		camelCase: 'borderShape',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	bottom: {
		name: 'bottom',
		camelCase: 'bottom',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'box-decoration-break': {
		name: 'box-decoration-break',
		camelCase: 'boxDecorationBreak',
		inherited: false,
		keywords: ['slice', 'clone'],
		initialValue: '',
		acceptsNegative: false
	},
	'box-shadow': {
		name: 'box-shadow',
		camelCase: 'boxShadow',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'box-sizing': {
		name: 'box-sizing',
		camelCase: 'boxSizing',
		inherited: false,
		keywords: ['content-box', 'border-box'],
		initialValue: 'content-box',
		acceptsNegative: false
	},
	'break-after': {
		name: 'break-after',
		camelCase: 'breakAfter',
		inherited: false,
		keywords: [
			'auto',
			'avoid',
			'avoid-column',
			'avoid-page',
			'column',
			'left',
			'page',
			'recto',
			'right',
			'verso'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'break-before': {
		name: 'break-before',
		camelCase: 'breakBefore',
		inherited: false,
		keywords: [
			'auto',
			'avoid',
			'avoid-column',
			'avoid-page',
			'column',
			'left',
			'page',
			'recto',
			'right',
			'verso'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'break-inside': {
		name: 'break-inside',
		camelCase: 'breakInside',
		inherited: false,
		keywords: ['auto', 'avoid', 'avoid-column', 'avoid-page'],
		initialValue: '',
		acceptsNegative: false
	},
	'buffered-rendering': {
		name: 'buffered-rendering',
		camelCase: 'bufferedRendering',
		inherited: false,
		keywords: ['auto', 'dynamic', 'static'],
		initialValue: '',
		acceptsNegative: false
	},
	'caption-side': {
		name: 'caption-side',
		camelCase: 'captionSide',
		inherited: true,
		keywords: ['top', 'bottom'],
		initialValue: 'top',
		acceptsNegative: false
	},
	'caret-animation': {
		name: 'caret-animation',
		camelCase: 'caretAnimation',
		inherited: true,
		keywords: ['auto', 'manual'],
		initialValue: '',
		acceptsNegative: false
	},
	'caret-color': {
		name: 'caret-color',
		camelCase: 'caretColor',
		inherited: true,
		keywords: ['auto', 'currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'caret-shape': {
		name: 'caret-shape',
		camelCase: 'caretShape',
		inherited: true,
		keywords: ['auto', 'bar', 'block', 'underscore'],
		initialValue: '',
		acceptsNegative: false
	},
	clear: {
		name: 'clear',
		camelCase: 'clear',
		inherited: false,
		keywords: ['none', 'left', 'right', 'both', 'inline-start', 'inline-end'],
		initialValue: 'none',
		acceptsNegative: false
	},
	clip: {
		name: 'clip',
		camelCase: 'clip',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'clip-path': {
		name: 'clip-path',
		camelCase: 'clipPath',
		inherited: false,
		keywords: [
			'border-box',
			'padding-box',
			'content-box',
			'margin-box',
			'fill-box',
			'stroke-box',
			'view-box',
			'none'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'clip-rule': {
		name: 'clip-rule',
		camelCase: 'clipRule',
		inherited: true,
		keywords: ['nonzero', 'evenodd'],
		initialValue: '',
		acceptsNegative: false
	},
	'color-interpolation': {
		name: 'color-interpolation',
		camelCase: 'colorInterpolation',
		inherited: true,
		keywords: ['auto', 'srgb', 'linearrgb'],
		initialValue: '',
		acceptsNegative: false
	},
	'color-interpolation-filters': {
		name: 'color-interpolation-filters',
		camelCase: 'colorInterpolationFilters',
		inherited: true,
		keywords: ['auto', 'srgb', 'linearrgb'],
		initialValue: '',
		acceptsNegative: false
	},
	'color-rendering': {
		name: 'color-rendering',
		camelCase: 'colorRendering',
		inherited: true,
		keywords: ['auto', 'optimizespeed', 'optimizequality'],
		initialValue: '',
		acceptsNegative: false
	},
	'color-scheme': {
		name: 'color-scheme',
		camelCase: 'colorScheme',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'column-fill': {
		name: 'column-fill',
		camelCase: 'columnFill',
		inherited: false,
		keywords: ['balance', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	contain: {
		name: 'contain',
		camelCase: 'contain',
		inherited: false,
		keywords: [
			'none',
			'strict',
			'content',
			'size',
			'layout',
			'style',
			'paint',
			'inline-size',
			'block-size'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'contain-intrinsic-width': {
		name: 'contain-intrinsic-width',
		camelCase: 'containIntrinsicWidth',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'contain-intrinsic-height': {
		name: 'contain-intrinsic-height',
		camelCase: 'containIntrinsicHeight',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'container-name': {
		name: 'container-name',
		camelCase: 'containerName',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'container-type': {
		name: 'container-type',
		camelCase: 'containerType',
		inherited: false,
		keywords: ['normal', 'inline-size', 'size', 'scroll-state', 'anchored'],
		initialValue: '',
		acceptsNegative: false
	},
	content: {
		name: 'content',
		camelCase: 'content',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-bottom-left-shape': {
		name: 'corner-bottom-left-shape',
		camelCase: 'cornerBottomLeftShape',
		inherited: false,
		keywords: ['notch', 'scoop', 'bevel', 'round', 'squircle', 'square'],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-bottom-right-shape': {
		name: 'corner-bottom-right-shape',
		camelCase: 'cornerBottomRightShape',
		inherited: false,
		keywords: ['notch', 'scoop', 'bevel', 'round', 'squircle', 'square'],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-top-left-shape': {
		name: 'corner-top-left-shape',
		camelCase: 'cornerTopLeftShape',
		inherited: false,
		keywords: ['notch', 'scoop', 'bevel', 'round', 'squircle', 'square'],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-top-right-shape': {
		name: 'corner-top-right-shape',
		camelCase: 'cornerTopRightShape',
		inherited: false,
		keywords: ['notch', 'scoop', 'bevel', 'round', 'squircle', 'square'],
		initialValue: '',
		acceptsNegative: false
	},
	'counter-increment': {
		name: 'counter-increment',
		camelCase: 'counterIncrement',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'counter-reset': {
		name: 'counter-reset',
		camelCase: 'counterReset',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'counter-set': {
		name: 'counter-set',
		camelCase: 'counterSet',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	cursor: {
		name: 'cursor',
		camelCase: 'cursor',
		inherited: true,
		keywords: [
			'auto',
			'default',
			'none',
			'context-menu',
			'help',
			'pointer',
			'progress',
			'wait',
			'cell',
			'crosshair',
			'text',
			'vertical-text',
			'alias',
			'copy',
			'move',
			'no-drop',
			'not-allowed',
			'e-resize',
			'n-resize',
			'ne-resize',
			'nw-resize',
			's-resize',
			'se-resize',
			'sw-resize',
			'w-resize',
			'ew-resize',
			'ns-resize',
			'nesw-resize',
			'nwse-resize',
			'col-resize',
			'row-resize',
			'all-scroll',
			'zoom-in',
			'zoom-out',
			'grab',
			'grabbing'
		],
		initialValue: 'auto',
		acceptsNegative: false
	},
	cx: {
		name: 'cx',
		camelCase: 'cx',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	cy: {
		name: 'cy',
		camelCase: 'cy',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	d: {
		name: 'd',
		camelCase: 'd',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	display: {
		name: 'display',
		camelCase: 'display',
		inherited: false,
		keywords: [
			'inline',
			'block',
			'list-item',
			'inline-block',
			'table',
			'inline-table',
			'table-row-group',
			'table-header-group',
			'table-footer-group',
			'table-row',
			'table-column-group',
			'table-column',
			'table-cell',
			'table-caption',
			'-webkit-box',
			'-webkit-inline-box',
			'flex',
			'inline-flex',
			'grid',
			'inline-grid',
			'contents',
			'flow-root',
			'none',
			'flow',
			'math',
			'ruby',
			'ruby-text',
			'grid-lanes',
			'inline-grid-lanes'
		],
		initialValue: 'inline',
		acceptsNegative: false
	},
	'dominant-baseline': {
		name: 'dominant-baseline',
		camelCase: 'dominantBaseline',
		inherited: true,
		keywords: [
			'auto',
			'alphabetic',
			'ideographic',
			'middle',
			'central',
			'mathematical',
			'hanging',
			'use-script',
			'no-change',
			'reset-size',
			'text-after-edge',
			'text-before-edge'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'empty-cells': {
		name: 'empty-cells',
		camelCase: 'emptyCells',
		inherited: true,
		keywords: ['show', 'hide'],
		initialValue: 'show',
		acceptsNegative: false
	},
	fill: {
		name: 'fill',
		camelCase: 'fill',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'fill-opacity': {
		name: 'fill-opacity',
		camelCase: 'fillOpacity',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'fill-rule': {
		name: 'fill-rule',
		camelCase: 'fillRule',
		inherited: true,
		keywords: ['nonzero', 'evenodd'],
		initialValue: '',
		acceptsNegative: false
	},
	filter: {
		name: 'filter',
		camelCase: 'filter',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'flex-basis': {
		name: 'flex-basis',
		camelCase: 'flexBasis',
		inherited: false,
		keywords: ['auto', 'fit-content', 'min-content', 'max-content', 'content'],
		initialValue: '',
		acceptsNegative: false
	},
	'flex-direction': {
		name: 'flex-direction',
		camelCase: 'flexDirection',
		inherited: false,
		keywords: ['row', 'row-reverse', 'column', 'column-reverse'],
		initialValue: '',
		acceptsNegative: false
	},
	'flex-grow': {
		name: 'flex-grow',
		camelCase: 'flexGrow',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'flex-shrink': {
		name: 'flex-shrink',
		camelCase: 'flexShrink',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'flex-wrap': {
		name: 'flex-wrap',
		camelCase: 'flexWrap',
		inherited: false,
		keywords: ['nowrap', 'wrap', 'wrap-reverse', 'balance'],
		initialValue: '',
		acceptsNegative: false
	},
	float: {
		name: 'float',
		camelCase: 'cssFloat',
		inherited: false,
		keywords: ['none', 'left', 'right', 'inline-start', 'inline-end'],
		initialValue: 'none',
		acceptsNegative: false
	},
	'flood-color': {
		name: 'flood-color',
		camelCase: 'floodColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'flood-opacity': {
		name: 'flood-opacity',
		camelCase: 'floodOpacity',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'flow-tolerance': {
		name: 'flow-tolerance',
		camelCase: 'flowTolerance',
		inherited: false,
		keywords: ['normal', 'infinite'],
		initialValue: '',
		acceptsNegative: false
	},
	'frame-sizing': {
		name: 'frame-sizing',
		camelCase: 'frameSizing',
		inherited: false,
		keywords: [
			'auto',
			'content-width',
			'content-height',
			'content-block-size',
			'content-inline-size'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-auto-columns': {
		name: 'grid-auto-columns',
		camelCase: 'gridAutoColumns',
		inherited: false,
		keywords: ['auto', 'min-content', 'max-content'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-auto-flow': {
		name: 'grid-auto-flow',
		camelCase: 'gridAutoFlow',
		inherited: false,
		keywords: ['row', 'column'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-auto-rows': {
		name: 'grid-auto-rows',
		camelCase: 'gridAutoRows',
		inherited: false,
		keywords: ['auto', 'min-content', 'max-content'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-column-end': {
		name: 'grid-column-end',
		camelCase: 'gridColumnEnd',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'grid-column-start': {
		name: 'grid-column-start',
		camelCase: 'gridColumnStart',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'grid-lanes-direction': {
		name: 'grid-lanes-direction',
		camelCase: 'gridLanesDirection',
		inherited: false,
		keywords: ['normal', 'row', 'column', 'fill-reverse', 'track-reverse'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-lanes-pack': {
		name: 'grid-lanes-pack',
		camelCase: 'gridLanesPack',
		inherited: false,
		keywords: ['normal', 'dense'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-row-end': {
		name: 'grid-row-end',
		camelCase: 'gridRowEnd',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'grid-row-start': {
		name: 'grid-row-start',
		camelCase: 'gridRowStart',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'grid-template-areas': {
		name: 'grid-template-areas',
		camelCase: 'gridTemplateAreas',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-template-columns': {
		name: 'grid-template-columns',
		camelCase: 'gridTemplateColumns',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'grid-template-rows': {
		name: 'grid-template-rows',
		camelCase: 'gridTemplateRows',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	height: {
		name: 'height',
		camelCase: 'height',
		inherited: false,
		keywords: ['auto', 'fit-content', 'min-content', 'max-content'],
		initialValue: '',
		acceptsNegative: false
	},
	'hyphenate-limit-chars': {
		name: 'hyphenate-limit-chars',
		camelCase: 'hyphenateLimitChars',
		inherited: true,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'interest-delay-start': {
		name: 'interest-delay-start',
		camelCase: 'interestDelayStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'interest-delay-end': {
		name: 'interest-delay-end',
		camelCase: 'interestDelayEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	hyphens: {
		name: 'hyphens',
		camelCase: 'hyphens',
		inherited: true,
		keywords: ['none', 'manual', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'image-animation': {
		name: 'image-animation',
		camelCase: 'imageAnimation',
		inherited: true,
		keywords: ['normal', 'running', 'paused', 'stopped'],
		initialValue: '',
		acceptsNegative: false
	},
	'image-rendering': {
		name: 'image-rendering',
		camelCase: 'imageRendering',
		inherited: true,
		keywords: [
			'auto',
			'optimizespeed',
			'optimizequality',
			'-webkit-optimize-contrast',
			'pixelated',
			'crisp-edges'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'image-orientation': {
		name: 'image-orientation',
		camelCase: 'imageOrientation',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'dynamic-range-limit': {
		name: 'dynamic-range-limit',
		camelCase: 'dynamicRangeLimit',
		inherited: true,
		keywords: ['standard', 'no-limit', 'constrained'],
		initialValue: '',
		acceptsNegative: false
	},
	'initial-letter': {
		name: 'initial-letter',
		camelCase: 'initialLetter',
		inherited: false,
		keywords: ['drop', 'normal', 'raise'],
		initialValue: '',
		acceptsNegative: false
	},
	interactivity: {
		name: 'interactivity',
		camelCase: 'interactivity',
		inherited: true,
		keywords: ['auto', 'inert'],
		initialValue: '',
		acceptsNegative: false
	},
	'interpolate-size': {
		name: 'interpolate-size',
		camelCase: 'interpolateSize',
		inherited: true,
		keywords: ['numeric-only', 'allow-keywords'],
		initialValue: '',
		acceptsNegative: false
	},
	isolation: {
		name: 'isolation',
		camelCase: 'isolation',
		inherited: false,
		keywords: ['auto', 'isolate'],
		initialValue: '',
		acceptsNegative: false
	},
	'justify-content': {
		name: 'justify-content',
		camelCase: 'justifyContent',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'justify-items': {
		name: 'justify-items',
		camelCase: 'justifyItems',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'justify-self': {
		name: 'justify-self',
		camelCase: 'justifySelf',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	left: {
		name: 'left',
		camelCase: 'left',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'letter-spacing': {
		name: 'letter-spacing',
		camelCase: 'letterSpacing',
		inherited: true,
		keywords: ['normal'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'lighting-color': {
		name: 'lighting-color',
		camelCase: 'lightingColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'line-height': {
		name: 'line-height',
		camelCase: 'lineHeight',
		inherited: true,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'list-style-image': {
		name: 'list-style-image',
		camelCase: 'listStyleImage',
		inherited: true,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'list-style-position': {
		name: 'list-style-position',
		camelCase: 'listStylePosition',
		inherited: true,
		keywords: ['outside', 'inside'],
		initialValue: 'outside',
		acceptsNegative: false
	},
	'list-style-type': {
		name: 'list-style-type',
		camelCase: 'listStyleType',
		inherited: true,
		keywords: [
			'disc',
			'circle',
			'square',
			'disclosure-open',
			'disclosure-closed',
			'decimal',
			'none'
		],
		initialValue: 'disc',
		acceptsNegative: false
	},
	'margin-bottom': {
		name: 'margin-bottom',
		camelCase: 'marginBottom',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'margin-left': {
		name: 'margin-left',
		camelCase: 'marginLeft',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'margin-right': {
		name: 'margin-right',
		camelCase: 'marginRight',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'margin-top': {
		name: 'margin-top',
		camelCase: 'marginTop',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'margin-trim': {
		name: 'margin-trim',
		camelCase: 'marginTrim',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'marker-end': {
		name: 'marker-end',
		camelCase: 'markerEnd',
		inherited: true,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'marker-mid': {
		name: 'marker-mid',
		camelCase: 'markerMid',
		inherited: true,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'marker-start': {
		name: 'marker-start',
		camelCase: 'markerStart',
		inherited: true,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-type': {
		name: 'mask-type',
		camelCase: 'maskType',
		inherited: false,
		keywords: ['luminance', 'alpha'],
		initialValue: '',
		acceptsNegative: false
	},
	'math-shift': {
		name: 'math-shift',
		camelCase: 'mathShift',
		inherited: true,
		keywords: ['normal', 'compact'],
		initialValue: '',
		acceptsNegative: false
	},
	'math-style': {
		name: 'math-style',
		camelCase: 'mathStyle',
		inherited: true,
		keywords: ['normal', 'compact'],
		initialValue: '',
		acceptsNegative: false
	},
	'max-height': {
		name: 'max-height',
		camelCase: 'maxHeight',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'max-width': {
		name: 'max-width',
		camelCase: 'maxWidth',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'min-height': {
		name: 'min-height',
		camelCase: 'minHeight',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'min-width': {
		name: 'min-width',
		camelCase: 'minWidth',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'mix-blend-mode': {
		name: 'mix-blend-mode',
		camelCase: 'mixBlendMode',
		inherited: false,
		keywords: [
			'normal',
			'multiply',
			'screen',
			'overlay',
			'darken',
			'lighten',
			'color-dodge',
			'color-burn',
			'hard-light',
			'soft-light',
			'difference',
			'exclusion',
			'hue',
			'saturation',
			'color',
			'luminosity',
			'plus-lighter'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'object-fit': {
		name: 'object-fit',
		camelCase: 'objectFit',
		inherited: false,
		keywords: ['fill', 'contain', 'cover', 'none', 'scale-down'],
		initialValue: '',
		acceptsNegative: false
	},
	'object-position': {
		name: 'object-position',
		camelCase: 'objectPosition',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'object-view-box': {
		name: 'object-view-box',
		camelCase: 'objectViewBox',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'offset-anchor': {
		name: 'offset-anchor',
		camelCase: 'offsetAnchor',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'offset-distance': {
		name: 'offset-distance',
		camelCase: 'offsetDistance',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'offset-path': {
		name: 'offset-path',
		camelCase: 'offsetPath',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'offset-position': {
		name: 'offset-position',
		camelCase: 'offsetPosition',
		inherited: false,
		keywords: ['auto', 'normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'offset-rotate': {
		name: 'offset-rotate',
		camelCase: 'offsetRotate',
		inherited: false,
		keywords: ['auto', 'reverse'],
		initialValue: '',
		acceptsNegative: false
	},
	opacity: {
		name: 'opacity',
		camelCase: 'opacity',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	order: {
		name: 'order',
		camelCase: 'order',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'origin-trial-test-property': {
		name: 'origin-trial-test-property',
		camelCase: 'originTrialTestProperty',
		inherited: false,
		keywords: ['normal', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	orphans: {
		name: 'orphans',
		camelCase: 'orphans',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'outline-color': {
		name: 'outline-color',
		camelCase: 'outlineColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'outline-offset': {
		name: 'outline-offset',
		camelCase: 'outlineOffset',
		inherited: false,
		keywords: [],
		initialValue: '0px',
		acceptsNegative: true
	},
	'outline-style': {
		name: 'outline-style',
		camelCase: 'outlineStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'outline-width': {
		name: 'outline-width',
		camelCase: 'outlineWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '0px',
		acceptsNegative: false
	},
	'overflow-anchor': {
		name: 'overflow-anchor',
		camelCase: 'overflowAnchor',
		inherited: false,
		keywords: ['visible', 'none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'overflow-wrap': {
		name: 'overflow-wrap',
		camelCase: 'overflowWrap',
		inherited: true,
		keywords: ['normal', 'break-word', 'anywhere'],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'overflow-inline': {
		name: 'overflow-inline',
		camelCase: 'overflowInline',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'overflow-block': {
		name: 'overflow-block',
		camelCase: 'overflowBlock',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'overflow-clip-margin': {
		name: 'overflow-clip-margin',
		camelCase: 'overflowClipMargin',
		inherited: false,
		keywords: ['border-box', 'content-box', 'padding-box'],
		initialValue: '',
		acceptsNegative: false
	},
	'overflow-x': {
		name: 'overflow-x',
		camelCase: 'overflowX',
		inherited: false,
		keywords: ['visible', 'hidden', 'scroll', 'auto', 'overlay', 'clip'],
		initialValue: 'visible',
		acceptsNegative: false
	},
	'overflow-y': {
		name: 'overflow-y',
		camelCase: 'overflowY',
		inherited: false,
		keywords: ['visible', 'hidden', 'scroll', 'auto', 'overlay', 'clip'],
		initialValue: 'visible',
		acceptsNegative: false
	},
	'overscroll-behavior-inline': {
		name: 'overscroll-behavior-inline',
		camelCase: 'overscrollBehaviorInline',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'overscroll-behavior-block': {
		name: 'overscroll-behavior-block',
		camelCase: 'overscrollBehaviorBlock',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'overscroll-behavior-x': {
		name: 'overscroll-behavior-x',
		camelCase: 'overscrollBehaviorX',
		inherited: false,
		keywords: ['auto', 'contain', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'overscroll-behavior-y': {
		name: 'overscroll-behavior-y',
		camelCase: 'overscrollBehaviorY',
		inherited: false,
		keywords: ['auto', 'contain', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'padding-bottom': {
		name: 'padding-bottom',
		camelCase: 'paddingBottom',
		inherited: false,
		keywords: [],
		initialValue: '0px',
		acceptsNegative: false
	},
	'padding-left': {
		name: 'padding-left',
		camelCase: 'paddingLeft',
		inherited: false,
		keywords: [],
		initialValue: '0px',
		acceptsNegative: false
	},
	'padding-right': {
		name: 'padding-right',
		camelCase: 'paddingRight',
		inherited: false,
		keywords: [],
		initialValue: '0px',
		acceptsNegative: false
	},
	'padding-top': {
		name: 'padding-top',
		camelCase: 'paddingTop',
		inherited: false,
		keywords: [],
		initialValue: '0px',
		acceptsNegative: false
	},
	page: {
		name: 'page',
		camelCase: 'page',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'page-margin-safety': {
		name: 'page-margin-safety',
		camelCase: 'pageMarginSafety',
		inherited: false,
		keywords: ['none', 'clamp', 'add'],
		initialValue: '',
		acceptsNegative: false
	},
	'page-orientation': {
		name: 'page-orientation',
		camelCase: 'pageOrientation',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'paint-order': {
		name: 'paint-order',
		camelCase: 'paintOrder',
		inherited: true,
		keywords: ['normal', 'fill', 'stroke', 'markers'],
		initialValue: '',
		acceptsNegative: false
	},
	'path-length': {
		name: 'path-length',
		camelCase: 'pathLength',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	perspective: {
		name: 'perspective',
		camelCase: 'perspective',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'perspective-origin': {
		name: 'perspective-origin',
		camelCase: 'perspectiveOrigin',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'pointer-events': {
		name: 'pointer-events',
		camelCase: 'pointerEvents',
		inherited: true,
		keywords: [
			'none',
			'auto',
			'stroke',
			'fill',
			'painted',
			'visible',
			'visiblestroke',
			'visiblefill',
			'visiblepainted',
			'bounding-box',
			'all'
		],
		initialValue: '',
		acceptsNegative: false
	},
	position: {
		name: 'position',
		camelCase: 'position',
		inherited: false,
		keywords: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
		initialValue: 'static',
		acceptsNegative: false
	},
	'position-anchor': {
		name: 'position-anchor',
		camelCase: 'positionAnchor',
		inherited: false,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'position-try-fallbacks': {
		name: 'position-try-fallbacks',
		camelCase: 'positionTryFallbacks',
		inherited: false,
		keywords: ['none', 'flip-block', 'flip-inline', 'flip-start', 'flip-x', 'flip-y'],
		initialValue: '',
		acceptsNegative: false
	},
	'position-try-order': {
		name: 'position-try-order',
		camelCase: 'positionTryOrder',
		inherited: false,
		keywords: ['normal', 'most-width', 'most-height', 'most-block-size', 'most-inline-size'],
		initialValue: '',
		acceptsNegative: false
	},
	'position-visibility': {
		name: 'position-visibility',
		camelCase: 'positionVisibility',
		inherited: false,
		keywords: ['always', 'anchors-visible', 'no-overflow'],
		initialValue: '',
		acceptsNegative: false
	},
	'print-color-adjust': {
		name: 'print-color-adjust',
		camelCase: 'printColorAdjust',
		inherited: true,
		keywords: ['economy', 'exact'],
		initialValue: '',
		acceptsNegative: false
	},
	quotes: {
		name: 'quotes',
		camelCase: 'quotes',
		inherited: true,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'content-visibility': {
		name: 'content-visibility',
		camelCase: 'contentVisibility',
		inherited: false,
		keywords: ['visible', 'auto', 'hidden'],
		initialValue: '',
		acceptsNegative: false
	},
	'reading-flow': {
		name: 'reading-flow',
		camelCase: 'readingFlow',
		inherited: false,
		keywords: [
			'normal',
			'flex-visual',
			'flex-flow',
			'grid-rows',
			'grid-columns',
			'grid-order',
			'source-order'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'reading-order': {
		name: 'reading-order',
		camelCase: 'readingOrder',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	resize: {
		name: 'resize',
		camelCase: 'resize',
		inherited: false,
		keywords: ['none', 'both', 'horizontal', 'vertical', 'block', 'inline'],
		initialValue: 'none',
		acceptsNegative: false
	},
	right: {
		name: 'right',
		camelCase: 'right',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	r: {
		name: 'r',
		camelCase: 'r',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	rx: {
		name: 'rx',
		camelCase: 'rx',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	ry: {
		name: 'ry',
		camelCase: 'ry',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-target-group': {
		name: 'scroll-target-group',
		camelCase: 'scrollTargetGroup',
		inherited: false,
		keywords: ['none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-marker-group': {
		name: 'scroll-marker-group',
		camelCase: 'scrollMarkerGroup',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scrollbar-color': {
		name: 'scrollbar-color',
		camelCase: 'scrollbarColor',
		inherited: true,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scrollbar-gutter': {
		name: 'scrollbar-gutter',
		camelCase: 'scrollbarGutter',
		inherited: false,
		keywords: ['auto', 'stable', 'both-edges'],
		initialValue: '',
		acceptsNegative: false
	},
	'scrollbar-width': {
		name: 'scrollbar-width',
		camelCase: 'scrollbarWidth',
		inherited: false,
		keywords: ['auto', 'thin', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-behavior': {
		name: 'scroll-behavior',
		camelCase: 'scrollBehavior',
		inherited: false,
		keywords: ['auto', 'smooth'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-initial-target': {
		name: 'scroll-initial-target',
		camelCase: 'scrollInitialTarget',
		inherited: false,
		keywords: ['none', 'nearest'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-block-end': {
		name: 'scroll-margin-block-end',
		camelCase: 'scrollMarginBlockEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-block-start': {
		name: 'scroll-margin-block-start',
		camelCase: 'scrollMarginBlockStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-bottom': {
		name: 'scroll-margin-bottom',
		camelCase: 'scrollMarginBottom',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-inline-end': {
		name: 'scroll-margin-inline-end',
		camelCase: 'scrollMarginInlineEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-inline-start': {
		name: 'scroll-margin-inline-start',
		camelCase: 'scrollMarginInlineStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-left': {
		name: 'scroll-margin-left',
		camelCase: 'scrollMarginLeft',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-right': {
		name: 'scroll-margin-right',
		camelCase: 'scrollMarginRight',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-margin-top': {
		name: 'scroll-margin-top',
		camelCase: 'scrollMarginTop',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-block-end': {
		name: 'scroll-padding-block-end',
		camelCase: 'scrollPaddingBlockEnd',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-block-start': {
		name: 'scroll-padding-block-start',
		camelCase: 'scrollPaddingBlockStart',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-bottom': {
		name: 'scroll-padding-bottom',
		camelCase: 'scrollPaddingBottom',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-inline-end': {
		name: 'scroll-padding-inline-end',
		camelCase: 'scrollPaddingInlineEnd',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-inline-start': {
		name: 'scroll-padding-inline-start',
		camelCase: 'scrollPaddingInlineStart',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-left': {
		name: 'scroll-padding-left',
		camelCase: 'scrollPaddingLeft',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-right': {
		name: 'scroll-padding-right',
		camelCase: 'scrollPaddingRight',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-padding-top': {
		name: 'scroll-padding-top',
		camelCase: 'scrollPaddingTop',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-snap-align': {
		name: 'scroll-snap-align',
		camelCase: 'scrollSnapAlign',
		inherited: false,
		keywords: ['none', 'start', 'end', 'center'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-snap-stop': {
		name: 'scroll-snap-stop',
		camelCase: 'scrollSnapStop',
		inherited: false,
		keywords: ['normal', 'always'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-snap-type': {
		name: 'scroll-snap-type',
		camelCase: 'scrollSnapType',
		inherited: false,
		keywords: ['none', 'x', 'y', 'block', 'inline', 'both', 'mandatory', 'proximity'],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-timeline-axis': {
		name: 'scroll-timeline-axis',
		camelCase: 'scrollTimelineAxis',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'scroll-timeline-name': {
		name: 'scroll-timeline-name',
		camelCase: 'scrollTimelineName',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'shape-image-threshold': {
		name: 'shape-image-threshold',
		camelCase: 'shapeImageThreshold',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'shape-margin': {
		name: 'shape-margin',
		camelCase: 'shapeMargin',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'shape-outside': {
		name: 'shape-outside',
		camelCase: 'shapeOutside',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'shape-rendering': {
		name: 'shape-rendering',
		camelCase: 'shapeRendering',
		inherited: true,
		keywords: ['auto', 'optimizespeed', 'crispedges', 'geometricprecision'],
		initialValue: '',
		acceptsNegative: false
	},
	size: {
		name: 'size',
		camelCase: 'size',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	speak: {
		name: 'speak',
		camelCase: 'speak',
		inherited: true,
		keywords: ['none', 'normal', 'spell-out', 'digits', 'literal-punctuation', 'no-punctuation'],
		initialValue: '',
		acceptsNegative: false
	},
	'stop-color': {
		name: 'stop-color',
		camelCase: 'stopColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'stop-opacity': {
		name: 'stop-opacity',
		camelCase: 'stopOpacity',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	stroke: {
		name: 'stroke',
		camelCase: 'stroke',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-dasharray': {
		name: 'stroke-dasharray',
		camelCase: 'strokeDasharray',
		inherited: true,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-dashoffset': {
		name: 'stroke-dashoffset',
		camelCase: 'strokeDashoffset',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-linecap': {
		name: 'stroke-linecap',
		camelCase: 'strokeLinecap',
		inherited: true,
		keywords: ['butt', 'round', 'square'],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-linejoin': {
		name: 'stroke-linejoin',
		camelCase: 'strokeLinejoin',
		inherited: true,
		keywords: ['miter', 'bevel', 'round'],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-miterlimit': {
		name: 'stroke-miterlimit',
		camelCase: 'strokeMiterlimit',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-opacity': {
		name: 'stroke-opacity',
		camelCase: 'strokeOpacity',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'stroke-width': {
		name: 'stroke-width',
		camelCase: 'strokeWidth',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'table-layout': {
		name: 'table-layout',
		camelCase: 'tableLayout',
		inherited: false,
		keywords: ['auto', 'fixed'],
		initialValue: 'auto',
		acceptsNegative: false
	},
	'tab-size': {
		name: 'tab-size',
		camelCase: 'tabSize',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'text-align': {
		name: 'text-align',
		camelCase: 'textAlign',
		inherited: true,
		keywords: [
			'left',
			'right',
			'center',
			'justify',
			'-webkit-left',
			'-webkit-right',
			'-webkit-center',
			'start',
			'end',
			'match-parent'
		],
		initialValue: 'start',
		acceptsNegative: false
	},
	'text-align-last': {
		name: 'text-align-last',
		camelCase: 'textAlignLast',
		inherited: true,
		keywords: ['auto', 'start', 'end', 'left', 'right', 'center', 'justify', 'match-parent'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-anchor': {
		name: 'text-anchor',
		camelCase: 'textAnchor',
		inherited: true,
		keywords: ['start', 'middle', 'end'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-autospace': {
		name: 'text-autospace',
		camelCase: 'textAutospace',
		inherited: true,
		keywords: ['no-autospace', 'normal'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-box-edge': {
		name: 'text-box-edge',
		camelCase: 'textBoxEdge',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'text-box-trim': {
		name: 'text-box-trim',
		camelCase: 'textBoxTrim',
		inherited: false,
		keywords: ['none', 'trim-start', 'trim-end', 'trim-both'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-combine-upright': {
		name: 'text-combine-upright',
		camelCase: 'textCombineUpright',
		inherited: true,
		keywords: ['none', 'all'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-decoration-color': {
		name: 'text-decoration-color',
		camelCase: 'textDecorationColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-decoration-line': {
		name: 'text-decoration-line',
		camelCase: 'textDecorationLine',
		inherited: false,
		keywords: [
			'none',
			'underline',
			'overline',
			'line-through',
			'blink',
			'spelling-error',
			'grammar-error'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'text-decoration-skip-ink': {
		name: 'text-decoration-skip-ink',
		camelCase: 'textDecorationSkipInk',
		inherited: true,
		keywords: ['none', 'auto', 'all'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-decoration-style': {
		name: 'text-decoration-style',
		camelCase: 'textDecorationStyle',
		inherited: false,
		keywords: ['solid', 'double', 'dotted', 'dashed', 'wavy'],
		initialValue: 'solid',
		acceptsNegative: false
	},
	'text-decoration-thickness': {
		name: 'text-decoration-thickness',
		camelCase: 'textDecorationThickness',
		inherited: false,
		keywords: ['auto', 'from-font'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-indent': {
		name: 'text-indent',
		camelCase: 'textIndent',
		inherited: true,
		keywords: [],
		initialValue: '0px',
		acceptsNegative: true
	},
	'text-justify': {
		name: 'text-justify',
		camelCase: 'textJustify',
		inherited: true,
		keywords: ['auto', 'none', 'inter-word', 'inter-character'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-overflow': {
		name: 'text-overflow',
		camelCase: 'textOverflow',
		inherited: false,
		keywords: ['clip', 'ellipsis'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-shadow': {
		name: 'text-shadow',
		camelCase: 'textShadow',
		inherited: true,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-size-adjust': {
		name: 'text-size-adjust',
		camelCase: 'textSizeAdjust',
		inherited: true,
		keywords: ['none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-spacing-trim': {
		name: 'text-spacing-trim',
		camelCase: 'textSpacingTrim',
		inherited: true,
		keywords: ['normal', 'space-all', 'space-first', 'trim-start'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-transform': {
		name: 'text-transform',
		camelCase: 'textTransform',
		inherited: true,
		keywords: [
			'none',
			'capitalize',
			'uppercase',
			'lowercase',
			'full-width',
			'full-size-kana',
			'math-auto'
		],
		initialValue: 'none',
		acceptsNegative: false
	},
	'text-underline-offset': {
		name: 'text-underline-offset',
		camelCase: 'textUnderlineOffset',
		inherited: true,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-underline-position': {
		name: 'text-underline-position',
		camelCase: 'textUnderlinePosition',
		inherited: true,
		keywords: ['auto', 'from-font', 'under', 'left', 'right'],
		initialValue: '',
		acceptsNegative: false
	},
	'timeline-scope': {
		name: 'timeline-scope',
		camelCase: 'timelineScope',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	top: {
		name: 'top',
		camelCase: 'top',
		inherited: false,
		keywords: ['auto'],
		initialValue: '0px',
		acceptsNegative: true
	},
	overlay: {
		name: 'overlay',
		camelCase: 'overlay',
		inherited: false,
		keywords: ['none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'touch-action': {
		name: 'touch-action',
		camelCase: 'touchAction',
		inherited: false,
		keywords: [
			'auto',
			'none',
			'pan-x',
			'pan-left',
			'pan-right',
			'pan-y',
			'pan-up',
			'pan-down',
			'pinch-zoom',
			'manipulation'
		],
		initialValue: '',
		acceptsNegative: false
	},
	transform: {
		name: 'transform',
		camelCase: 'transform',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'transform-box': {
		name: 'transform-box',
		camelCase: 'transformBox',
		inherited: false,
		keywords: ['content-box', 'border-box', 'fill-box', 'stroke-box', 'view-box'],
		initialValue: '',
		acceptsNegative: false
	},
	'transform-origin': {
		name: 'transform-origin',
		camelCase: 'transformOrigin',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'transform-style': {
		name: 'transform-style',
		camelCase: 'transformStyle',
		inherited: false,
		keywords: ['flat', 'preserve-3d'],
		initialValue: '',
		acceptsNegative: false
	},
	translate: {
		name: 'translate',
		camelCase: 'translate',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	rotate: {
		name: 'rotate',
		camelCase: 'rotate',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	scale: {
		name: 'scale',
		camelCase: 'scale',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'unicode-bidi': {
		name: 'unicode-bidi',
		camelCase: 'unicodeBidi',
		inherited: false,
		keywords: ['normal', 'embed', 'bidi-override', 'isolate', 'plaintext', 'isolate-override'],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'vector-effect': {
		name: 'vector-effect',
		camelCase: 'vectorEffect',
		inherited: false,
		keywords: ['none', 'non-scaling-stroke'],
		initialValue: '',
		acceptsNegative: false
	},
	'vertical-align': {
		name: 'vertical-align',
		camelCase: 'verticalAlign',
		inherited: false,
		keywords: ['baseline', 'sub', 'super', 'text-top', 'text-bottom', 'middle'],
		initialValue: 'baseline',
		acceptsNegative: false
	},
	'view-timeline-axis': {
		name: 'view-timeline-axis',
		camelCase: 'viewTimelineAxis',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'view-timeline-inset': {
		name: 'view-timeline-inset',
		camelCase: 'viewTimelineInset',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'view-timeline-name': {
		name: 'view-timeline-name',
		camelCase: 'viewTimelineName',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'view-transition-class': {
		name: 'view-transition-class',
		camelCase: 'viewTransitionClass',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'view-transition-group': {
		name: 'view-transition-group',
		camelCase: 'viewTransitionGroup',
		inherited: false,
		keywords: ['normal', 'contain', 'nearest'],
		initialValue: '',
		acceptsNegative: false
	},
	'view-transition-name': {
		name: 'view-transition-name',
		camelCase: 'viewTransitionName',
		inherited: false,
		keywords: ['none', 'auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'view-transition-scope': {
		name: 'view-transition-scope',
		camelCase: 'viewTransitionScope',
		inherited: false,
		keywords: ['none', 'all'],
		initialValue: '',
		acceptsNegative: false
	},
	visibility: {
		name: 'visibility',
		camelCase: 'visibility',
		inherited: true,
		keywords: ['visible', 'hidden', 'collapse'],
		initialValue: 'visible',
		acceptsNegative: false
	},
	x: {
		name: 'x',
		camelCase: 'x',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	y: {
		name: 'y',
		camelCase: 'y',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	appearance: {
		name: 'appearance',
		camelCase: 'appearance',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'app-region': {
		name: 'app-region',
		camelCase: 'appRegion',
		inherited: false,
		keywords: ['none', 'drag', 'no-drag'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-border-horizontal-spacing': {
		name: '-webkit-border-horizontal-spacing',
		camelCase: 'webkitBorderHorizontalSpacing',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-border-image': {
		name: '-webkit-border-image',
		camelCase: 'webkitBorderImage',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-border-vertical-spacing': {
		name: '-webkit-border-vertical-spacing',
		camelCase: 'webkitBorderVerticalSpacing',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-align': {
		name: '-webkit-box-align',
		camelCase: 'webkitBoxAlign',
		inherited: false,
		keywords: ['stretch', 'start', 'center', 'end', 'baseline'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-decoration-break': {
		name: '-webkit-box-decoration-break',
		camelCase: 'webkitBoxDecorationBreak',
		inherited: false,
		keywords: ['slice', 'clone'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-direction': {
		name: '-webkit-box-direction',
		camelCase: 'webkitBoxDirection',
		inherited: false,
		keywords: ['normal', 'reverse'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-flex': {
		name: '-webkit-box-flex',
		camelCase: 'webkitBoxFlex',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-ordinal-group': {
		name: '-webkit-box-ordinal-group',
		camelCase: 'webkitBoxOrdinalGroup',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-orient': {
		name: '-webkit-box-orient',
		camelCase: 'webkitBoxOrient',
		inherited: false,
		keywords: ['horizontal', 'vertical'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-pack': {
		name: '-webkit-box-pack',
		camelCase: 'webkitBoxPack',
		inherited: false,
		keywords: ['start', 'center', 'end', 'justify'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-box-reflect': {
		name: '-webkit-box-reflect',
		camelCase: 'webkitBoxReflect',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'column-count': {
		name: 'column-count',
		camelCase: 'columnCount',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-gap': {
		name: 'column-gap',
		camelCase: 'columnGap',
		inherited: false,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: true
	},
	'row-gap': {
		name: 'row-gap',
		camelCase: 'rowGap',
		inherited: false,
		keywords: ['normal'],
		initialValue: '',
		acceptsNegative: true
	},
	'rule-overlap': {
		name: 'rule-overlap',
		camelCase: 'ruleOverlap',
		inherited: false,
		keywords: ['row-over-column', 'column-over-row'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-break': {
		name: 'column-rule-break',
		camelCase: 'columnRuleBreak',
		inherited: false,
		keywords: ['none', 'normal', 'intersection'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-break': {
		name: 'row-rule-break',
		camelCase: 'rowRuleBreak',
		inherited: false,
		keywords: ['none', 'normal', 'intersection'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-edge-inset-end': {
		name: 'column-rule-edge-inset-end',
		camelCase: 'columnRuleEdgeInsetEnd',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-edge-inset-end': {
		name: 'row-rule-edge-inset-end',
		camelCase: 'rowRuleEdgeInsetEnd',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-edge-inset-start': {
		name: 'column-rule-edge-inset-start',
		camelCase: 'columnRuleEdgeInsetStart',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-edge-inset-start': {
		name: 'row-rule-edge-inset-start',
		camelCase: 'rowRuleEdgeInsetStart',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-interior-inset-end': {
		name: 'column-rule-interior-inset-end',
		camelCase: 'columnRuleInteriorInsetEnd',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-interior-inset-end': {
		name: 'row-rule-interior-inset-end',
		camelCase: 'rowRuleInteriorInsetEnd',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-interior-inset-start': {
		name: 'column-rule-interior-inset-start',
		camelCase: 'columnRuleInteriorInsetStart',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-interior-inset-start': {
		name: 'row-rule-interior-inset-start',
		camelCase: 'rowRuleInteriorInsetStart',
		inherited: false,
		keywords: ['overlap-join'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-color': {
		name: 'column-rule-color',
		camelCase: 'columnRuleColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-color': {
		name: 'row-rule-color',
		camelCase: 'rowRuleColor',
		inherited: false,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-style': {
		name: 'column-rule-style',
		camelCase: 'columnRuleStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-style': {
		name: 'row-rule-style',
		camelCase: 'rowRuleStyle',
		inherited: false,
		keywords: [
			'none',
			'hidden',
			'inset',
			'groove',
			'outset',
			'ridge',
			'dotted',
			'dashed',
			'solid',
			'double'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-visibility-items': {
		name: 'column-rule-visibility-items',
		camelCase: 'columnRuleVisibilityItems',
		inherited: false,
		keywords: ['all', 'auto', 'around', 'between'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-visibility-items': {
		name: 'row-rule-visibility-items',
		camelCase: 'rowRuleVisibilityItems',
		inherited: false,
		keywords: ['all', 'auto', 'around', 'between'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-rule-width': {
		name: 'column-rule-width',
		camelCase: 'columnRuleWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '',
		acceptsNegative: false
	},
	'row-rule-width': {
		name: 'row-rule-width',
		camelCase: 'rowRuleWidth',
		inherited: false,
		keywords: ['thin', 'medium', 'thick'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-span': {
		name: 'column-span',
		camelCase: 'columnSpan',
		inherited: false,
		keywords: ['none', 'all'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-width': {
		name: 'column-width',
		camelCase: 'columnWidth',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-height': {
		name: 'column-height',
		camelCase: 'columnHeight',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'column-wrap': {
		name: 'column-wrap',
		camelCase: 'columnWrap',
		inherited: false,
		keywords: ['auto', 'nowrap', 'wrap'],
		initialValue: '',
		acceptsNegative: false
	},
	'hyphenate-character': {
		name: 'hyphenate-character',
		camelCase: 'hyphenateCharacter',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-line-break': {
		name: '-webkit-line-break',
		camelCase: 'webkitLineBreak',
		inherited: false,
		keywords: ['auto', 'loose', 'normal', 'strict', 'after-white-space'],
		initialValue: '',
		acceptsNegative: false
	},
	'line-break': {
		name: 'line-break',
		camelCase: 'lineBreak',
		inherited: true,
		keywords: ['auto', 'loose', 'normal', 'strict', 'anywhere', 'after-white-space'],
		initialValue: '',
		acceptsNegative: false
	},
	continue: {
		name: 'continue',
		camelCase: 'continue',
		inherited: false,
		keywords: ['auto', 'collapse', '-webkit-legacy'],
		initialValue: '',
		acceptsNegative: false
	},
	'max-lines': {
		name: 'max-lines',
		camelCase: 'maxLines',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'block-ellipsis': {
		name: 'block-ellipsis',
		camelCase: 'blockEllipsis',
		inherited: true,
		keywords: ['auto', 'no-ellipsis'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-line-clamp': {
		name: '-webkit-line-clamp',
		camelCase: 'webkitLineClamp',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-box-image-outset': {
		name: '-webkit-mask-box-image-outset',
		camelCase: 'webkitMaskBoxImageOutset',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-box-image-repeat': {
		name: '-webkit-mask-box-image-repeat',
		camelCase: 'webkitMaskBoxImageRepeat',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-box-image-slice': {
		name: '-webkit-mask-box-image-slice',
		camelCase: 'webkitMaskBoxImageSlice',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-box-image-source': {
		name: '-webkit-mask-box-image-source',
		camelCase: 'webkitMaskBoxImageSource',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-box-image-width': {
		name: '-webkit-mask-box-image-width',
		camelCase: 'webkitMaskBoxImageWidth',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-mode': {
		name: 'mask-mode',
		camelCase: 'maskMode',
		inherited: false,
		keywords: ['alpha', 'luminance', 'match-source'],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-clip': {
		name: 'mask-clip',
		camelCase: 'maskClip',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-composite': {
		name: 'mask-composite',
		camelCase: 'maskComposite',
		inherited: false,
		keywords: ['add', 'subtract', 'intersect', 'exclude'],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-image': {
		name: 'mask-image',
		camelCase: 'maskImage',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-origin': {
		name: 'mask-origin',
		camelCase: 'maskOrigin',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-position-x': {
		name: '-webkit-mask-position-x',
		camelCase: 'webkitMaskPositionX',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-mask-position-y': {
		name: '-webkit-mask-position-y',
		camelCase: 'webkitMaskPositionY',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-repeat': {
		name: 'mask-repeat',
		camelCase: 'maskRepeat',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'mask-size': {
		name: 'mask-size',
		camelCase: 'maskSize',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-perspective-origin-x': {
		name: '-webkit-perspective-origin-x',
		camelCase: 'webkitPerspectiveOriginX',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-perspective-origin-y': {
		name: '-webkit-perspective-origin-y',
		camelCase: 'webkitPerspectiveOriginY',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-rtl-ordering': {
		name: '-webkit-rtl-ordering',
		camelCase: 'webkitRtlOrdering',
		inherited: true,
		keywords: ['logical', 'visual'],
		initialValue: '',
		acceptsNegative: false
	},
	'ruby-align': {
		name: 'ruby-align',
		camelCase: 'rubyAlign',
		inherited: true,
		keywords: ['space-around', 'start', 'center', 'space-between'],
		initialValue: '',
		acceptsNegative: false
	},
	'ruby-overhang': {
		name: 'ruby-overhang',
		camelCase: 'rubyOverhang',
		inherited: true,
		keywords: ['auto', 'none'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-ruby-position': {
		name: '-webkit-ruby-position',
		camelCase: 'webkitRubyPosition',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'ruby-position': {
		name: 'ruby-position',
		camelCase: 'rubyPosition',
		inherited: true,
		keywords: ['over', 'under'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-tap-highlight-color': {
		name: '-webkit-tap-highlight-color',
		camelCase: 'webkitTapHighlightColor',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-combine': {
		name: '-webkit-text-combine',
		camelCase: 'webkitTextCombine',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'text-emphasis-color': {
		name: 'text-emphasis-color',
		camelCase: 'textEmphasisColor',
		inherited: true,
		keywords: ['currentcolor'],
		initialValue: '',
		acceptsNegative: false
	},
	'text-emphasis-position': {
		name: 'text-emphasis-position',
		camelCase: 'textEmphasisPosition',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'text-emphasis-style': {
		name: 'text-emphasis-style',
		camelCase: 'textEmphasisStyle',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-fill-color': {
		name: '-webkit-text-fill-color',
		camelCase: 'webkitTextFillColor',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'text-fit': {
		name: 'text-fit',
		camelCase: 'textFit',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-security': {
		name: '-webkit-text-security',
		camelCase: 'webkitTextSecurity',
		inherited: true,
		keywords: ['none', 'disc', 'circle', 'square'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-stroke-color': {
		name: '-webkit-text-stroke-color',
		camelCase: 'webkitTextStrokeColor',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-stroke-width': {
		name: '-webkit-text-stroke-width',
		camelCase: 'webkitTextStrokeWidth',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-transform-origin-x': {
		name: '-webkit-transform-origin-x',
		camelCase: 'webkitTransformOriginX',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-transform-origin-y': {
		name: '-webkit-transform-origin-y',
		camelCase: 'webkitTransformOriginY',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-transform-origin-z': {
		name: '-webkit-transform-origin-z',
		camelCase: 'webkitTransformOriginZ',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-user-drag': {
		name: '-webkit-user-drag',
		camelCase: 'webkitUserDrag',
		inherited: false,
		keywords: ['auto', 'none', 'element'],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-user-modify': {
		name: '-webkit-user-modify',
		camelCase: 'webkitUserModify',
		inherited: true,
		keywords: ['read-only', 'read-write', 'read-write-plaintext-only'],
		initialValue: '',
		acceptsNegative: false
	},
	'user-select': {
		name: 'user-select',
		camelCase: 'userSelect',
		inherited: true,
		keywords: ['auto', 'none', 'text', 'all', 'contain'],
		initialValue: '',
		acceptsNegative: false
	},
	'white-space-collapse': {
		name: 'white-space-collapse',
		camelCase: 'whiteSpaceCollapse',
		inherited: true,
		keywords: ['collapse', 'preserve', 'preserve-breaks', 'break-spaces'],
		initialValue: 'collapse',
		acceptsNegative: false
	},
	'text-wrap-mode': {
		name: 'text-wrap-mode',
		camelCase: 'textWrapMode',
		inherited: true,
		keywords: ['wrap', 'nowrap'],
		initialValue: 'wrap',
		acceptsNegative: false
	},
	'text-wrap-style': {
		name: 'text-wrap-style',
		camelCase: 'textWrapStyle',
		inherited: true,
		keywords: ['auto', 'balance', 'pretty', 'stable'],
		initialValue: '',
		acceptsNegative: false
	},
	widows: {
		name: 'widows',
		camelCase: 'widows',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	width: {
		name: 'width',
		camelCase: 'width',
		inherited: false,
		keywords: ['auto', 'fit-content', 'min-content', 'max-content'],
		initialValue: '',
		acceptsNegative: false
	},
	'will-change': {
		name: 'will-change',
		camelCase: 'willChange',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'word-break': {
		name: 'word-break',
		camelCase: 'wordBreak',
		inherited: true,
		keywords: ['normal', 'break-all', 'keep-all', 'break-word', 'auto-phrase'],
		initialValue: 'normal',
		acceptsNegative: false
	},
	'word-spacing': {
		name: 'word-spacing',
		camelCase: 'wordSpacing',
		inherited: true,
		keywords: ['normal'],
		initialValue: '0px',
		acceptsNegative: true
	},
	'z-index': {
		name: 'z-index',
		camelCase: 'zIndex',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'inline-size': {
		name: 'inline-size',
		camelCase: 'inlineSize',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'block-size': {
		name: 'block-size',
		camelCase: 'blockSize',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: false
	},
	'min-inline-size': {
		name: 'min-inline-size',
		camelCase: 'minInlineSize',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'min-block-size': {
		name: 'min-block-size',
		camelCase: 'minBlockSize',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'max-inline-size': {
		name: 'max-inline-size',
		camelCase: 'maxInlineSize',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'max-block-size': {
		name: 'max-block-size',
		camelCase: 'maxBlockSize',
		inherited: false,
		keywords: ['none'],
		initialValue: '',
		acceptsNegative: false
	},
	'margin-inline-start': {
		name: 'margin-inline-start',
		camelCase: 'marginInlineStart',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'margin-inline-end': {
		name: 'margin-inline-end',
		camelCase: 'marginInlineEnd',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'margin-block-start': {
		name: 'margin-block-start',
		camelCase: 'marginBlockStart',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'margin-block-end': {
		name: 'margin-block-end',
		camelCase: 'marginBlockEnd',
		inherited: false,
		keywords: ['auto'],
		initialValue: '',
		acceptsNegative: true
	},
	'padding-inline-start': {
		name: 'padding-inline-start',
		camelCase: 'paddingInlineStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'padding-inline-end': {
		name: 'padding-inline-end',
		camelCase: 'paddingInlineEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'padding-block-start': {
		name: 'padding-block-start',
		camelCase: 'paddingBlockStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'padding-block-end': {
		name: 'padding-block-end',
		camelCase: 'paddingBlockEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-inline-start-width': {
		name: 'border-inline-start-width',
		camelCase: 'borderInlineStartWidth',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-inline-start-style': {
		name: 'border-inline-start-style',
		camelCase: 'borderInlineStartStyle',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-inline-start-color': {
		name: 'border-inline-start-color',
		camelCase: 'borderInlineStartColor',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-inline-end-width': {
		name: 'border-inline-end-width',
		camelCase: 'borderInlineEndWidth',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-inline-end-style': {
		name: 'border-inline-end-style',
		camelCase: 'borderInlineEndStyle',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-inline-end-color': {
		name: 'border-inline-end-color',
		camelCase: 'borderInlineEndColor',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-block-start-width': {
		name: 'border-block-start-width',
		camelCase: 'borderBlockStartWidth',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-block-start-style': {
		name: 'border-block-start-style',
		camelCase: 'borderBlockStartStyle',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-block-start-color': {
		name: 'border-block-start-color',
		camelCase: 'borderBlockStartColor',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-block-end-width': {
		name: 'border-block-end-width',
		camelCase: 'borderBlockEndWidth',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-block-end-style': {
		name: 'border-block-end-style',
		camelCase: 'borderBlockEndStyle',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-block-end-color': {
		name: 'border-block-end-color',
		camelCase: 'borderBlockEndColor',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'inset-inline-start': {
		name: 'inset-inline-start',
		camelCase: 'insetInlineStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'inset-inline-end': {
		name: 'inset-inline-end',
		camelCase: 'insetInlineEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'inset-block-start': {
		name: 'inset-block-start',
		camelCase: 'insetBlockStart',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'inset-block-end': {
		name: 'inset-block-end',
		camelCase: 'insetBlockEnd',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: true
	},
	'border-start-start-radius': {
		name: 'border-start-start-radius',
		camelCase: 'borderStartStartRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-start-end-radius': {
		name: 'border-start-end-radius',
		camelCase: 'borderStartEndRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-end-start-radius': {
		name: 'border-end-start-radius',
		camelCase: 'borderEndStartRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'border-end-end-radius': {
		name: 'border-end-end-radius',
		camelCase: 'borderEndEndRadius',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-start-start-shape': {
		name: 'corner-start-start-shape',
		camelCase: 'cornerStartStartShape',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-start-end-shape': {
		name: 'corner-start-end-shape',
		camelCase: 'cornerStartEndShape',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-end-start-shape': {
		name: 'corner-end-start-shape',
		camelCase: 'cornerEndStartShape',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'corner-end-end-shape': {
		name: 'corner-end-end-shape',
		camelCase: 'cornerEndEndShape',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	all: {
		name: 'all',
		camelCase: 'all',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'-webkit-text-decorations-in-effect': {
		name: '-webkit-text-decorations-in-effect',
		camelCase: 'webkitTextDecorationsInEffect',
		inherited: true,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'position-area': {
		name: 'position-area',
		camelCase: 'positionArea',
		inherited: false,
		keywords: [
			'none',
			'top',
			'bottom',
			'center',
			'left',
			'right',
			'x-start',
			'x-end',
			'y-start',
			'y-end',
			'start',
			'end',
			'self-start',
			'self-end',
			'all'
		],
		initialValue: '',
		acceptsNegative: false
	},
	'contain-intrinsic-inline-size': {
		name: 'contain-intrinsic-inline-size',
		camelCase: 'containIntrinsicInlineSize',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	},
	'contain-intrinsic-block-size': {
		name: 'contain-intrinsic-block-size',
		camelCase: 'containIntrinsicBlockSize',
		inherited: false,
		keywords: [],
		initialValue: '',
		acceptsNegative: false
	}
};
/**
 * Fast keyword lookup: property name → valid keywords.
 */
export const CSS_PROPERTY_KEYWORDS = {};
for (const [name, meta] of Object.entries(CSS_LONGHAND_PROPERTIES)) {
	if (meta.keywords.length > 0) {
		CSS_PROPERTY_KEYWORDS[name] = new Set(meta.keywords);
	}
}
