/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by happy-dom-codegen from Chromium's css_properties.json5.
 * Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5
 */
import CSSStyleDeclarationPropertySetParser from './CSSStyleDeclarationPropertySetParser.js';
import CSSStyleDeclarationPropertyGetParser from './CSSStyleDeclarationPropertyGetParser.js';
import CSSStyleDeclarationCSSParser from '../css-parser/CSSStyleDeclarationCSSParser.js';
import { CSS_SHORTHAND_TO_LONGHANDS } from '../property-definitions/CSSShorthandDefinitions.js';
import { CSS_ALIAS_TO_CANONICAL } from '../property-definitions/CSSAliasDefinitions.js';
/**
 * Shorthands that toString() will attempt to collapse longhands into.
 */
const COLLAPSE_SHORTHANDS = [
	'margin',
	'padding',
	'border',
	'border-width',
	'border-style',
	'border-color',
	'border-image',
	'border-radius',
	'outline',
	'flex',
	'flex-flow',
	'overflow',
	'gap',
	'place-content',
	'place-items',
	'place-self',
	'background',
	'font',
	'text-decoration',
	'list-style',
	'columns',
	'overscroll-behavior',
	'inset',
	'margin-block',
	'margin-inline',
	'padding-block',
	'padding-inline',
	'inset-block',
	'inset-inline',
	'scroll-margin',
	'scroll-padding',
	'border-top',
	'border-right',
	'border-bottom',
	'border-left',
	'font-variant'
];
/**
 * Manages CSS property storage. Only longhands are stored internally.
 *
 * Orchestrates all behavioral contracts:
 * - B1: set() decomposes shorthands via SetParser
 * - B2: get() recomposes shorthands via GetParser
 * - B3: Longhand override naturally invalidates shorthands (consequence of B2)
 * - B4: remove() clears longhands (all for shorthand, one for longhand)
 * - B6: Invalid values are silently ignored (SetParser returns null)
 * - B7: Empty value removes property
 * - B8: Priority propagates through shorthand expansion
 * - B9: toString() collapses longhands into shorthands
 * - B10: length/item track stored longhands
 * - B12: Custom properties (--*) stored alongside standard properties
 * - B13: Aliases resolved to canonical names
 */
export default class CSSStyleDeclarationPropertyManager {
	#properties = {};
	#propertyNames = [];
	/**
	 * Returns the underlying property store (used by computed style).
	 */
	get properties() {
		return this.#properties;
	}
	/**
	 * Constructor.
	 *
	 * @param [options] Options.
	 * @param [options.cssText] CSS string.
	 */
	constructor(options) {
		if (options?.cssText) {
			const { rules } = CSSStyleDeclarationCSSParser.parse(options.cssText);
			for (const rule of rules) {
				if (rule.important || !this.get(rule.name)?.important) {
					this.set(rule.name, rule.value, rule.important);
				}
			}
		}
	}
	/**
	 * Returns property value.
	 *
	 * @param name Property name.
	 * @returns Property value.
	 */
	get(name) {
		// Resolve alias (B13)
		const canonical = CSS_ALIAS_TO_CANONICAL[name] ?? name;
		// Direct longhand lookup
		if (this.#properties[canonical]) {
			return this.#properties[canonical];
		}
		// Shorthand recomposition (B2)
		const longhands = CSS_SHORTHAND_TO_LONGHANDS[canonical];
		if (longhands) {
			return CSSStyleDeclarationPropertyGetParser.get(canonical, this.#properties);
		}
		return null;
	}
	/**
	 * Sets a property value.
	 *
	 * @param name Property name.
	 * @param value Property value.
	 * @param important Whether the value has !important.
	 */
	set(name, value, important) {
		// Resolve alias (B13)
		const canonical = CSS_ALIAS_TO_CANONICAL[name] ?? name;
		// Empty value removes (B7)
		if (value === null || value === undefined || value.trim() === '') {
			this.remove(canonical);
			return;
		}
		// Parse and validate (B1, B6)
		const parsed = CSSStyleDeclarationPropertySetParser.parse(canonical, value, important);
		// Invalid value — silently ignore (B6)
		if (!parsed) {
			return;
		}
		// Store the resulting longhands
		for (const [propName, propValue] of Object.entries(parsed)) {
			if (propValue) {
				if (!this.#properties[propName]) {
					this.#propertyNames.push(propName);
				}
				this.#properties[propName] = propValue;
			}
		}
	}
	/**
	 * Removes a property.
	 *
	 * @param name Property name.
	 */
	remove(name) {
		// Resolve alias
		const canonical = CSS_ALIAS_TO_CANONICAL[name] ?? name;
		// Check if it's a shorthand — remove all longhands (B4)
		const longhands = CSS_SHORTHAND_TO_LONGHANDS[canonical];
		if (longhands) {
			for (const lh of longhands) {
				delete this.#properties[lh];
				const idx = this.#propertyNames.indexOf(lh);
				if (idx !== -1) {
					this.#propertyNames.splice(idx, 1);
				}
				// Also recursively remove if this longhand is itself a shorthand
				const subLonghands = CSS_SHORTHAND_TO_LONGHANDS[lh];
				if (subLonghands) {
					for (const sub of subLonghands) {
						delete this.#properties[sub];
						const subIdx = this.#propertyNames.indexOf(sub);
						if (subIdx !== -1) {
							this.#propertyNames.splice(subIdx, 1);
						}
					}
				}
			}
		}
		// Remove the property itself (longhand or custom property)
		delete this.#properties[canonical];
		const idx = this.#propertyNames.indexOf(canonical);
		if (idx !== -1) {
			this.#propertyNames.splice(idx, 1);
		}
	}
	/**
	 * Returns item.
	 *
	 * @param index Index.
	 * @returns Item.
	 */
	item(index) {
		return this.#propertyNames[index] || '';
	}
	/**
	 * Returns size.
	 *
	 * @returns Size.
	 */
	size() {
		return this.#propertyNames.length;
	}
	/**
	 * Returns CSS text.
	 *
	 * @returns CSS text.
	 */
	toString() {
		const used = new Set();
		const parts = [];
		for (const shorthand of COLLAPSE_SHORTHANDS) {
			const longhands = CSS_SHORTHAND_TO_LONGHANDS[shorthand];
			if (!longhands) {
				continue;
			}
			// Check if all longhands are present and none are already used
			const allPresent = longhands.every((lh) => this.#properties[lh] && !used.has(lh));
			if (!allPresent) {
				continue;
			}
			const composed = CSSStyleDeclarationPropertyGetParser.get(shorthand, this.#properties);
			if (composed) {
				for (const lh of longhands) {
					used.add(lh);
				}
				const imp = composed.important ? ' !important' : '';
				parts.push(`${shorthand}: ${composed.value}${imp};`);
			}
		}
		// Output remaining longhands
		for (const name of this.#propertyNames) {
			if (used.has(name)) {
				continue;
			}
			const prop = this.#properties[name];
			if (!prop) {
				continue;
			}
			const imp = prop.important ? ' !important' : '';
			parts.push(`${name}: ${prop.value}${imp};`);
		}
		return parts.join(' ');
	}
}
