/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by happy-dom-codegen from Chromium's css_properties.json5.
 * Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5
 */
import { CSS_PROPERTY_KEYWORDS } from '../property-definitions/CSSPropertyDefinitions.js';
/**
 * Validates and normalizes CSS values.
 * Enforces B5 (normalization), B6 (invalid values silently ignored).
 */
export default class CSSStyleDeclarationValueParser {
	/** CSS-wide (global) values accepted by all properties. */
	static GLOBAL_VALUES = new Set(['inherit', 'initial', 'unset', 'revert', 'revert-layer']);
	/** Regex for CSS variable references: var(--name) or var(--name, fallback). */
	static VAR_REGEXP = /^var\(\s*--[a-zA-Z0-9_-]+/;
	/** Regex for a valid CSS length value. */
	static LENGTH_REGEXP =
		/^(-?\d*\.?\d+)(px|em|rem|%|vw|vh|vmin|vmax|cm|mm|in|pt|pc|Q|ex|ch|cap|ic|lh|rlh|vi|vb|svw|svh|lvw|lvh|dvw|dvh|cqw|cqh|cqi|cqb|cqmin|cqmax)$/i;
	/** Regex for a valid number. */
	static NUMBER_REGEXP = /^-?\d*\.?\d+$/;
	/** Regex for a valid integer. */
	static INTEGER_REGEXP = /^-?\d+$/;
	/** Regex for calc() expression. */
	static CALC_REGEXP = /^calc\(.+\)$/i;
	/** Regex for a valid URL value. */
	static URL_REGEXP = /^url\(\s*(['"]?).*?\1\s*\)$/i;
	/** Regex for hex color. */
	static HEX_COLOR_REGEXP = /^#([0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/i;
	/** Regex for functional color values: rgb(), rgba(), hsl(), hsla(), etc. */
	static COLOR_FUNCTION_REGEXP =
		/^(rgb|rgba|hsl|hsla|hwb|lab|lch|oklch|oklab|color|color-mix|light-dark)\(/i;
	/** Named CSS colors. */
	static NAMED_COLORS = new Set([
		'transparent',
		'currentcolor',
		'aliceblue',
		'antiquewhite',
		'aqua',
		'aquamarine',
		'azure',
		'beige',
		'bisque',
		'black',
		'blanchedalmond',
		'blue',
		'blueviolet',
		'brown',
		'burlywood',
		'cadetblue',
		'chartreuse',
		'chocolate',
		'coral',
		'cornflowerblue',
		'cornsilk',
		'crimson',
		'cyan',
		'darkblue',
		'darkcyan',
		'darkgoldenrod',
		'darkgray',
		'darkgreen',
		'darkgrey',
		'darkkhaki',
		'darkmagenta',
		'darkolivegreen',
		'darkorange',
		'darkorchid',
		'darkred',
		'darksalmon',
		'darkseagreen',
		'darkslateblue',
		'darkslategray',
		'darkslategrey',
		'darkturquoise',
		'darkviolet',
		'deeppink',
		'deepskyblue',
		'dimgray',
		'dimgrey',
		'dodgerblue',
		'firebrick',
		'floralwhite',
		'forestgreen',
		'fuchsia',
		'gainsboro',
		'ghostwhite',
		'gold',
		'goldenrod',
		'gray',
		'green',
		'greenyellow',
		'grey',
		'honeydew',
		'hotpink',
		'indianred',
		'indigo',
		'ivory',
		'khaki',
		'lavender',
		'lavenderblush',
		'lawngreen',
		'lemonchiffon',
		'lightblue',
		'lightcoral',
		'lightcyan',
		'lightgoldenrodyellow',
		'lightgray',
		'lightgreen',
		'lightgrey',
		'lightpink',
		'lightsalmon',
		'lightseagreen',
		'lightskyblue',
		'lightslategray',
		'lightslategrey',
		'lightsteelblue',
		'lightyellow',
		'lime',
		'limegreen',
		'linen',
		'magenta',
		'maroon',
		'mediumaquamarine',
		'mediumblue',
		'mediumorchid',
		'mediumpurple',
		'mediumseagreen',
		'mediumslateblue',
		'mediumspringgreen',
		'mediumturquoise',
		'mediumvioletred',
		'midnightblue',
		'mintcream',
		'mistyrose',
		'moccasin',
		'navajowhite',
		'navy',
		'oldlace',
		'olive',
		'olivedrab',
		'orange',
		'orangered',
		'orchid',
		'palegoldenrod',
		'palegreen',
		'paleturquoise',
		'palevioletred',
		'papayawhip',
		'peachpuff',
		'peru',
		'pink',
		'plum',
		'powderblue',
		'purple',
		'rebeccapurple',
		'red',
		'rosybrown',
		'royalblue',
		'saddlebrown',
		'salmon',
		'sandybrown',
		'seagreen',
		'seashell',
		'sienna',
		'silver',
		'skyblue',
		'slateblue',
		'slategray',
		'slategrey',
		'snow',
		'springgreen',
		'steelblue',
		'tan',
		'teal',
		'thistle',
		'tomato',
		'turquoise',
		'violet',
		'wheat',
		'white',
		'whitesmoke',
		'yellow',
		'yellowgreen'
	]);
	/**
	 * Check if a value is a CSS-wide global keyword.
	 * @param value
	 */
	static getGlobal(value) {
		const lower = value.trim().toLowerCase();
		return this.GLOBAL_VALUES.has(lower) ? lower : null;
	}
	/**
	 * Check if a value is a CSS variable reference.
	 * @param value
	 */
	static getVariable(value) {
		const trimmed = value.trim();
		return this.VAR_REGEXP.test(trimmed) ? trimmed : null;
	}
	/**
	 * Parse a value as a valid CSS length, percentage, or 'auto', or 0.
	 * Returns the normalized value or null if invalid.
	 * @param value
	 * @param acceptNegative
	 */
	static getLength(value, acceptNegative = true) {
		const trimmed = value.trim().toLowerCase();
		if (trimmed === '0') {
			return '0px';
		}
		if (this.CALC_REGEXP.test(trimmed)) {
			return trimmed;
		}
		const match = this.LENGTH_REGEXP.exec(trimmed);
		if (!match) {
			return null;
		}
		const num = parseFloat(match[1]);
		if (!acceptNegative && num < 0) {
			return null;
		}
		if (num === 0) {
			return '0px';
		}
		return match[1] + match[2].toLowerCase();
	}
	/**
	 * Parse a value as length, percentage, auto, or content keywords.
	 * @param value
	 * @param acceptNegative
	 */
	static getContentMeasurement(value, acceptNegative = true) {
		const trimmed = value.trim().toLowerCase();
		if (
			trimmed === 'auto' ||
			trimmed === 'min-content' ||
			trimmed === 'max-content' ||
			trimmed === 'fit-content' ||
			trimmed === 'none'
		) {
			return trimmed;
		}
		if (trimmed.startsWith('fit-content(')) {
			return trimmed;
		}
		return this.getLength(trimmed, acceptNegative);
	}
	/**
	 * Parse a number value.
	 * @param value
	 * @param acceptNegative
	 */
	static getNumber(value, acceptNegative = true) {
		const trimmed = value.trim();
		if (!this.NUMBER_REGEXP.test(trimmed)) {
			return null;
		}
		const num = parseFloat(trimmed);
		if (!acceptNegative && num < 0) {
			return null;
		}
		return String(num);
	}
	/**
	 * Parse an integer value.
	 * @param value
	 * @param acceptNegative
	 */
	static getInteger(value, acceptNegative = true) {
		const trimmed = value.trim();
		if (!this.INTEGER_REGEXP.test(trimmed)) {
			return null;
		}
		const num = parseInt(trimmed, 10);
		if (!acceptNegative && num < 0) {
			return null;
		}
		return String(num);
	}
	/**
	 * Parse a CSS color value.
	 * @param value
	 */
	static getColor(value) {
		const trimmed = value.trim();
		const lower = trimmed.toLowerCase();
		// Named colors
		if (this.NAMED_COLORS.has(lower)) {
			return lower;
		}
		// Hex colors
		if (this.HEX_COLOR_REGEXP.test(lower)) {
			return lower;
		}
		// Functional colors (rgb, hsl, etc.)
		if (this.COLOR_FUNCTION_REGEXP.test(trimmed)) {
			// Basic validation: has matching parens
			let depth = 0;
			for (const ch of trimmed) {
				if (ch === '(') {
					depth++;
				}
				if (ch === ')') {
					depth--;
				}
			}
			if (depth === 0) {
				// Normalize spacing after commas: "rgba(0,55,1,0.5)" → "rgba(0, 55, 1, 0.5)"
				return trimmed.replace(/,\s*/g, ', ');
			}
		}
		return null;
	}
	/**
	 * Parse a URL value.
	 * @param value
	 */
	static getURL(value) {
		const trimmed = value.trim();
		if (!this.URL_REGEXP.test(trimmed)) {
			return null;
		}
		// Normalize URL quotes: url(path) → url("path"), url('path') → url("path")
		const inner = trimmed.slice(4, -1).trim();
		if (inner.startsWith('"') || inner.startsWith("'")) {
			// Already quoted — normalize to double quotes
			const unquoted = inner.slice(1, -1);
			return `url("${unquoted}")`;
		}
		return `url("${inner}")`;
	}
	/**
	 * Validate a value against a property's keyword list.
	 * Returns the normalized (lowercased) keyword or null.
	 * @param propertyName
	 * @param value
	 */
	static getKeyword(propertyName, value) {
		const keywords = CSS_PROPERTY_KEYWORDS[propertyName];
		if (!keywords) {
			return null;
		}
		const lower = value.trim().toLowerCase();
		return keywords.has(lower) ? lower : null;
	}
	/**
	 * Validate a value for a generic property (tries global, variable, keyword).
	 * @param propertyName
	 * @param value
	 */
	static validate(propertyName, value) {
		const trimmed = value.trim();
		if (!trimmed) {
			return null;
		}
		return (
			this.getVariable(trimmed) ??
			this.getGlobal(trimmed) ??
			this.getKeyword(propertyName, trimmed) ??
			null
		);
	}
}
