/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by happy-dom-codegen from Chromium's css_properties.json5.
 * Source: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/css_properties.json5
 */
import DOMExceptionNameEnum from '../../exception/DOMExceptionNameEnum.js';
import CSSStyleDeclarationPropertyManager from './property-manager/CSSStyleDeclarationPropertyManager.js';
import * as PropertySymbol from '../../PropertySymbol.js';
import CSSStyleDeclarationComputedStyle from './computed-style/CSSStyleDeclarationComputedStyle.js';
import CSSStyleDeclarationPropertyNameMap from './property-definitions/CSSStyleDeclarationPropertyNameMap.js';
/**
 * CSS Style Declaration.
 *
 * Implements the CSSOM CSSStyleDeclaration interface using a Proxy.
 * All 735 CSS properties are accessible via camelCase, kebab-case,
 * and numeric index notation. Type declarations provide full IDE support.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration
 */
export default class CSSStyleDeclaration {
	// Public properties
	parentRule = null;
	// Internal properties
	[PropertySymbol.window];
	// Private properties
	#element;
	#computed;
	#cache = {
		attributeValue: null,
		propertyManager: null
	};
	/**
	 * Converts a camelCase or PascalCase string to kebab-case.
	 * "marginTop" → "margin-top", "webkitTransform" → "-webkit-transform"
	 * @param name
	 */
	static #camelToKebab(name) {
		if (name === 'cssFloat') {
			return 'float';
		}
		let result = name.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
		if (result.startsWith('webkit-') || result.startsWith('moz-') || result.startsWith('ms-')) {
			result = '-' + result;
		}
		return result;
	}
	/**
	 * Proxy handler for CSS property access.
	 */
	static #PROXY_HANDLER = {
		get(target, prop, _receiver) {
			if (typeof prop === 'symbol') {
				return Reflect.get(target, prop, target);
			}
			// Numeric index access: style[0] returns property name, style[n >= length] returns undefined
			if (/^\d+$/.test(prop)) {
				const index = parseInt(prop, 10);
				if (index >= target.length) {
					return undefined;
				}
				return target.item(index);
			}
			// Known camelCase CSS property (checked before class members because
			// `declare` stubs make the property appear on the target but have no value)
			const kebab = CSSStyleDeclarationPropertyNameMap[prop];
			if (kebab !== undefined) {
				return target.getPropertyValue(kebab);
			}
			// Class members (methods, getters) pass through directly
			if (prop in target) {
				const value = Reflect.get(target, prop, target);
				// Bind methods so that `this` refers to the real target (not the Proxy),
				// which is required for private field access.
				if (typeof value === 'function') {
					return value.bind(target);
				}
				return value;
			}
			// Kebab-case string access: style['margin-top']
			if (prop.includes('-')) {
				return target.getPropertyValue(prop);
			}
			// Unknown camelCase — try converting to kebab and querying
			const guessKebab = CSSStyleDeclaration.#camelToKebab(prop);
			if (guessKebab !== prop) {
				return target.getPropertyValue(guessKebab);
			}
			return Reflect.get(target, prop, target);
		},
		set(target, prop, value, _receiver) {
			if (typeof prop === 'symbol') {
				return Reflect.set(target, prop, value, target);
			}
			// cssText pass through (uses setter with private fields)
			if (prop === 'cssText') {
				target.cssText = String(value ?? '');
				return true;
			}
			// Known camelCase CSS property
			const kebab = CSSStyleDeclarationPropertyNameMap[prop];
			if (kebab !== undefined) {
				target.setProperty(kebab, String(value ?? ''));
				return true;
			}
			// Kebab-case string access
			if (prop.includes('-')) {
				target.setProperty(prop, String(value ?? ''));
				return true;
			}
			// Unknown camelCase — try converting
			const guessKebab = CSSStyleDeclaration.#camelToKebab(prop);
			if (guessKebab !== prop) {
				target.setProperty(guessKebab, String(value ?? ''));
				return true;
			}
			return Reflect.set(target, prop, value, target);
		}
	};
	/**
	 * Constructor.
	 *
	 * @param illegalConstructorSymbol Illegal constructor symbol.
	 * @param window Window.
	 * @param [options] Options.
	 * @param [options.element] Element.
	 * @param [options.computed] Computed.
	 */
	constructor(illegalConstructorSymbol, window, options) {
		if (illegalConstructorSymbol !== PropertySymbol.illegalConstructor) {
			throw new TypeError('Illegal constructor');
		}
		this[PropertySymbol.window] = window;
		this.#element = options?.element || null;
		this.#computed = options?.element ? !!options?.computed : false;
		return new Proxy(this, CSSStyleDeclaration.#PROXY_HANDLER);
	}
	/**
	 * Returns length.
	 *
	 * @returns Length.
	 */
	get length() {
		return this.#getPropertyManager().size();
	}
	/**
	 * Returns the style declaration as a CSS text.
	 *
	 * @returns CSS text.
	 */
	get cssText() {
		if (this.#element && this.#computed) {
			return '';
		}
		return this.#getPropertyManager().toString();
	}
	/**
	 * Sets CSS text.
	 *
	 * @param cssText CSS text.
	 */
	set cssText(cssText) {
		if (this.#computed) {
			throw new this[PropertySymbol.window].DOMException(
				`Failed to execute 'cssText' on 'CSSStyleDeclaration': These styles are computed, and the properties are therefore read-only.`,
				DOMExceptionNameEnum.domException
			);
		}
		if (this.#element) {
			this.#cache.propertyManager = new CSSStyleDeclarationPropertyManager({ cssText });
			this.#cache.attributeValue = cssText;
			this.#element.setAttribute('style', this.#cache.propertyManager.toString());
		} else {
			this.#cache.propertyManager = new CSSStyleDeclarationPropertyManager({ cssText });
		}
	}
	/**
	 * Returns item.
	 *
	 * @param index Index.
	 * @returns Item.
	 */
	item(index) {
		return this.#getPropertyManager().item(index);
	}
	/**
	 * Set a property.
	 *
	 * @param name Property name.
	 * @param value Value. Must not contain "!important" as that should be set using the priority parameter.
	 * @param [priority] Can be "important", or an empty string.
	 */
	setProperty(name, value, priority) {
		if (this.#computed) {
			throw new this[PropertySymbol.window].DOMException(
				`Failed to execute 'setProperty' on 'CSSStyleDeclaration': These styles are computed, and therefore the '${name}' property is read-only.`,
				DOMExceptionNameEnum.domException
			);
		}
		if (priority !== '' && priority !== undefined && priority !== 'important') {
			return;
		}
		const stringValue = String(value).trim();
		const propertyManager = this.#getPropertyManager();
		if (stringValue) {
			propertyManager.set(name, stringValue, !!priority);
		} else {
			propertyManager.remove(name);
		}
		if (this.#element) {
			this.#cache.attributeValue = propertyManager.toString();
			if (this.#cache.attributeValue) {
				this.#element.setAttribute('style', this.#cache.attributeValue);
			} else {
				this.#element.removeAttribute('style');
			}
		}
	}
	/**
	 * Removes a property.
	 *
	 * @param name Property name in kebab case.
	 * @returns The value of the property before removal.
	 */
	removeProperty(name) {
		if (this.#computed) {
			throw new this[PropertySymbol.window].DOMException(
				`Failed to execute 'removeProperty' on 'CSSStyleDeclaration': These styles are computed, and therefore the '${name}' property is read-only.`,
				DOMExceptionNameEnum.domException
			);
		}
		const propertyManager = this.#getPropertyManager();
		const oldValue = propertyManager.get(name)?.value || '';
		propertyManager.remove(name);
		if (this.#element) {
			this.#cache.attributeValue = propertyManager.toString();
			if (this.#cache.attributeValue) {
				this.#element.setAttribute('style', this.#cache.attributeValue);
			} else {
				this.#element.removeAttribute('style');
			}
		}
		return oldValue;
	}
	/**
	 * Returns a property value.
	 *
	 * @param name Property name in kebab case.
	 * @returns Property value.
	 */
	getPropertyValue(name) {
		return this.#getPropertyManager().get(name)?.value || '';
	}
	/**
	 * Returns a property priority.
	 *
	 * @param name Property name in kebab case.
	 * @returns "important" if set to be important.
	 */
	getPropertyPriority(name) {
		return this.#getPropertyManager().get(name)?.important ? 'important' : '';
	}
	/**
	 * Returns property manager.
	 *
	 * @returns Property manager.
	 */
	#getPropertyManager() {
		const element = this.#element;
		const cache = this.#cache;
		if (!element) {
			if (!cache.propertyManager) {
				cache.propertyManager = new CSSStyleDeclarationPropertyManager();
			}
			return cache.propertyManager;
		}
		if (this.#computed) {
			return new CSSStyleDeclarationComputedStyle(element).getComputedStyle();
		}
		const attributeValue = element.getAttribute('style') || '';
		if (cache.attributeValue !== attributeValue) {
			cache.propertyManager = new CSSStyleDeclarationPropertyManager({ cssText: attributeValue });
		}
		return cache.propertyManager;
	}
}
